### ISSUE TITLE
Concerns with moving the response task to sub folder playbooks

### ISSUE THREAD

**Issue by socologize** [splunk/security_content#1041]
Since we are working to combine these tasks with different platforms. I would like to understand how they are integrating at the API request level.  Can you provide additional guidance?

**Comment by socologize** [comment]
https://github.com/splunk/security-content/tree/develop/response_tasks/playbooks

**Comment by josehelps** [comment]
@socologize this is currently an unfinished portion of content, also it is not served by the API the moment. As we continue to develop this feature we will release documentation on how it operates. Unfortunately do not have better guidance for you at the moment.
