### ISSUE TITLE
Splunk Enterprise Security not appending to Splunk Datamodels

### ISSUE THREAD

**Issue by emkaxon** [splunk/security_content#1083]
![image](https://user-images.githubusercontent.com/77234209/104125504-99666800-5370-11eb-933e-c6f8a38ae7d6.png)

Hello guys, I just deployed enterprise security and when checking the analytical stories, I am having an issue in appending them to the corresponding datamodel. I've tried generating excessive failed logins on my splunk instance.
The event was generated when I ran  **"| from datamodel:"Authentication"."Failed_Authentication" | stats values(tag) as "tag",dc(user) as "user_count",dc(dest) as "dest_count",count by "app","src" | where 'count'>=2" in the search and reporting app**

But the problem is that no notable event was generated on ES
Although I have enabled the correlation search and scheduled it to run every 5 minutes, and the condition was met. 
When I manually create a notable event from an existing event, all goes well and a notable is generated in the incident review feed
However, any correlation search addressing the datamodels does not generate a notable event

**Comment by patel-bhavin** [comment]
Hello @emkaxon : Thank you for reaching out. This correlation search and the associated analytic story is shipped out of the ES package and does not originate from ESCU package. Please reach out to the ES team to get this issue resolved!
