### ISSUE TITLE
Detect Path Interception By Creation Of program exe - Greedy regex

### ISSUE THREAD

**Issue by Jil** [splunk/security_content#1158]
When `services.exe` creates a child process, this correlation search extracts the executable that the Windows service is supposed to run and compares the `process_name`. Should they not match, an event is raised.

The issue occurs when the command line defined in the service contains an executable as an argument. The regex used being greedy, it catches the argument instead of the service definition, and raises an event when it should not, as the `process_name` actually matches the service definition.

Example of service definition causing the regex to fail :

```\"C:\Program Files (x86)\AlwaysUp\AlwaysUpService.exe\"  \"artIntGPAO (managed by AlwaysUpService)\" \"\\"C:\XXX\YYYY - YYYY\IntegrateurGpao.exe\\"\" -k -m -w \"C:\XXX\YYYY - YYYY\" -rn -f 3 0 -fd 5 `1```

In that case, `IntegrateurGpao.exe` is matched instead of `AlwaysUpService.exe`.

Proposal of fix for the regex : `^.*?\\(?<service_process>[^\\]*\.(?:exe|bat|com|ps1))`

**Comment by P4T12ICK** [comment]
That is great feedback. Thank you.

**Comment by patel-bhavin** [comment]
@Jil : Hello Jill, the proposed regex is incorrect in splunk. Would you know why is it failing?

![image](https://user-images.githubusercontent.com/7771446/108127067-8590de80-705f-11eb-8169-0617e694f361.png)

**Comment by Jil** [comment]
Yes, you have to double the backslashes because of Splunk escaping requirements

**Comment by patel-bhavin** [comment]
this search has been updated with your suggested fix. Thank you @Jil for the feedback
