### ISSUE TITLE
Links in mitremap comments broken

### ISSUE THREAD

**Issue by josehelps** [splunk/security_content#1173]
Once we moved to detection sub-objects eg endpoint, application, network, etc.. the mitremap comment link broke:
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/1476868/106922903-8595f380-66db-11eb-8854-79397ec0c8a3.png">

**Comment by patel-bhavin** [comment]
Nice!! Got that updated and tested in https://github.com/splunk/security_content/pull/1409. Thx
