### ISSUE TITLE
Splunk Security Content coverage map

### ISSUE THREAD

**Issue by rbecwar** [splunk/security_content#1408]
The Splunk Security Content coverage map uses the Attack Navigator and is at v4.1 (hxxps://mitremap.splunkresearch.com/) The MITRE ATT&CK navigator is at 4.3 (hxxps://mitre-attack.github.io/attack-navigator/) and has the new mapping to ATT&CK v9.

**Comment by patel-bhavin** [comment]
We gotta wait on [attack-navigator](https://github.com/mitre-attack//tree/master/layers) to update to. 4.3

**Comment by josehelps** [comment]
I think this is all done, navigator is now 4.3 :smile:
