### ISSUE TITLE
Suspicious MSBuild Rename / Name not checked

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#1451]
The "Suspicious MSBuild Rename" search lists all invocations of msbuild but does not actually check if the file was renamed. This leads to a lot of FPs when you have developers which use Visual Studio that has a different path for msbuild.

Please change 
`sysmon` EventID=1 (OriginalFileName=msbuild.exe OR process_name=msbuild.exe) .. 
to 
`sysmon` EventID=1 OriginalFileName=msbuild.exe process_name!=msbuild.exe ... 

I think this was originally intended by that search :-)

**Comment by MHaggis** [comment]
Thank you! We'll get these two out in the release tomorrow!
