### ISSUE TITLE
Reflection.Assembly can be loaded without the System. prefix

### ISSUE THREAD

**Issue by aquar5** [splunk/security_content#1494]
Hi, I'd like to suggest an improvement to the rule:

PowerShell Loading DotNET into Memory via System Reflection Assembly.

It's looking for a pattern [system.reflection.assembly]

I've seen malicious code using a simplified [reflection.assembly], please consider including it.

References:
https://attack.mitre.org/software/S0379/

Thanks.

**Comment by MHaggis** [comment]
Thank you! I'll get this out in the next release.

**Comment by MHaggis** [comment]
All set! It's been updated and out the gate.
