### ISSUE TITLE
Create local admin accounts using net exe / Logic Flaw

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#1519]
Hi

The search "Create local admin accounts using net exe" is not yet optimal.. 

for example it triggers when you just query users or groups.
Example: 
`net user JohnWayne /domain`
`net localgroup administrators`

I see two issues with the current version of that search: 
1. The operation "add local admin" consists of two parts: a) add a new user  b) add that user to the local admin group. its difficult to efficiently catch both steps in one query.
2. The admin groups are localized and differ between different language versions of Windows.

For 1) I would focus on the "add existing user to admin group" because that step is more likely to be malicious.
for 2) I can think of two possible solutions: 
a) just add the most likely languages. This is a universal approach and also works well in a 'mixed' environment that has machines with different languages but it needs a long list.
b) just put the name of the local admingroup into a macro and let the ES users localize the macro to the languages used.

So I suggest to change the current logic 
` .. where 
 (Processes.process_name=net.exe  OR Processes.process_name=net1.exe)  
 AND (Processes.process=*localgroup* OR Processes.process=*/add*
   OR Processes.process=*user*) by .. `

to something like this:
` .. where 
 (Processes.process_name=net.exe  OR Processes.process_name=net1.exe)  
 AND Processes.process=*/add*
 AND (Processes.process=*administrators* OR Processes.process=*administratoren*
 OR Processes.process=*administrateurs* OR Processes.process=*administrador* 
 OR Processes.process=*amministratori* OR Processes.process=*administratorer*) 
 by .. `
(covered here: english, german, french, spanish, italian, danish)

What do you think?

BTW:  the wildcard search in the current/old version  (*user*) also matches for wuauserv service (Windows Update Service) .. so "net stop/start wauauserv" will also trigger here..

**Comment by patel-bhavin** [comment]
Thanks for the suggestion : Created a PR : https://github.com/splunk/security_content/pull/1648
