### ISSUE TITLE
Detect Renamed WinRAR / Common Exe Name

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#1524]
It turned out that "winrar.exe" also seems to be pretty popular certain versions of WinRAR. :-)

Suggested change 
` .. EventID=1 (Product=WinRAR OR OriginalFileName=WinRAR.exe) process_name!=rar.exe .. `
to 
`... EventID=1 (Product=WinRAR OR OriginalFileName=WinRAR.exe) process_name!=rar.exe  process_name!=winrar.exe ..`

**Comment by MHaggis** [comment]
All set! Thank you for the assist!
