### ISSUE TITLE
Detect Renamed PSExec / Common Name

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#1525]
The original 64-bit Version of PSExec is called "psexec64.exe" 

See curl https://live.sysinternals.com/ | grep psexec

so let's change 
`EventID=1 (OriginalFileName=psexec.c process_name!=psexec.exe )`
to 
`EventID=1 (OriginalFileName=psexec.c process_name!=psexec.exe process_name!=PsExec64.exe)`

**Comment by MHaggis** [comment]
All set! Thank you for the assist!
