### ISSUE TITLE
Excessive number of distinct processes created in Windows Temp folder / Path rather than Cmdline

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#1526]
This search matches for all processes that contain "Windows\Temp\" somewhere in their command line. 

I get tons of FPs because the windows temp folder is used by a legit program as part of an argument.

How about changing the search from the commandline to the actual process path?
From 
`.. from datamodel=Endpoint.Processes where Processes.process = "*\\Windows\\Temp\\*" by .. `
to 
`.. from datamodel=Endpoint.Processes where Processes.process_path = "*\\Windows\\Temp\\*" by.. `

**Comment by mvelazc0** [comment]
Hello @mschilt  ! Apologies on the late reply. Thanks for the feedback, that makes a lot of sense. Let me do some testing and will revert back on this thread.

**Comment by mvelazc0** [comment]
Fixed it on a new PR. Automated testing passed.
