### ISSUE TITLE
Notes on "System Information Discovery Detection"

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#1527]
Hi

I like that search. In theory..  In practice there are some issues: 

1) 
There should be an alias the  multivalue field process:
`.. | stats values(process) AS process .. `   (or maybe use 'processes' since there are more than one ?)

This simplifies filtering a lot because referencing values(process) is not really handy.

2) 
Please also add the parent process. There is some (legitimate) Software that is running these commands.
Whitelisting by parent process is much easier here. 

Thanks

**Comment by josehelps** [comment]
@mschilt thank you again for the great feedback, I have started a PR with these changes here: https://github.com/splunk/security_content/pull/1643.

**Comment by mschilt** [comment]
looks good to me now. thanks.

**Comment by patel-bhavin** [comment]
Updated the SPL logic for better output. Here are the results! this way you can now whitelist parent process names correctly


![image](https://user-images.githubusercontent.com/7771446/132576560-7d6a8b5c-7bb6-4146-ab71-41ed6ffe0bd1.png)
