### ISSUE TITLE
Process Creating LNK file in Suspicious Location / Suggestion

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#1557]
Hi

The rule description states that it is triggering for suspicious files in under `C:\User*`
  or `*\Local\Temp\*` but in fact it only checks for *.lnk files under C:\temp\

Can we change this rule from 
`.. where Filesystem.file_name="*.lnk" AND Filesystem.file_path="C:\\Temp*"  by .. `
to something like this
`.. where Filesystem.file_name="*.lnk" AND (Filesystem.file_path="C:\\User\\*" OR Filesystem.file_path="*\\Temp\\*")  by .. `

Thanks

**Comment by mschilt** [comment]
Me again.. after playing a bit more with that rule I stumbled on another issue: 
The two searches are joined via the process ID.. Process IDs roll over quickly are not a stable key to join log tuples of the same process.. With enough endpoints tons of collisions are expected.

In a 'Sysmon' env I would join them via the process GUID (because that is present in Event 1 and Event 11). 
What do you think?

**Comment by josehelps** [comment]
@mschilt although I agree, and this seems to be available through the endpoint data model as field:  `process_guid` https://docs.splunk.com/Documentation/CIM/4.20.1/User/Endpoint. Let me run some tests, but prepped a change here https://github.com/splunk/security_content/pull/1590. Thank you so much for sharing and raising this!

**Comment by patel-bhavin** [comment]
after some SPL tweaks to your PR @d1vious : it passed our detection testing
Thank you both
