### ISSUE TITLE
Typo in correlation search "ESCU - Certutil exe certificate extraction - Rule"

### ISSUE THREAD

**Issue by my2ndhead** [splunk/security_content#1588]
Search is missing a by-clause before `Processes.dest`: 
`[ESCU - Certutil exe certificate extraction - Rule]
… 
search = | tstats `security_content_summariesonly` count min(_time) as firstTime values(Processes.process) as process max(_time) as lastTime from datamodel=Endpoint.Processes where Processes.process_name=certutil.exe Processes.process = &#34;* -exportPFX *&#34;  Processes.dest Processes.user Processes.parent_process Processes.process_name Processes.process Processes.process_id Processes.parent_process_id| `drop_dm_object_name(&#34;Processes&#34;)` | `security_content_ctime(firstTime)` |`security_content_ctime(lastTime)` | `certutil_exe_certificate_extraction_filter``

**Comment by MHaggis** [comment]
Hi @my2ndhead , it looks like the by is in the latest here - https://github.com/splunk/security_content/blob/develop/detections/endpoint/certutil_exe_certificate_extraction.yml
Do you happen to have an older release?

**Comment by my2ndhead** [comment]
Using the latest on Splunkbase (3.27.0). This fix obviously didn't make it into that release.

**Comment by MHaggis** [comment]
Yes, you are correct. I apparently updated it [here](https://github.com/splunk/security_content/pull/1567) because I saw the same error you did. Great minds! I appreciate you notifying us!
