### ISSUE TITLE
Detect Credit Card Numbers Using Luhn Algorithm - mixed up odds and evens?

### ISSUE THREAD

**Issue by kennykentaur** [splunk/security_content#1589]
I re-used the SPL from https://docs.splunksecurityessentials.com/content-detail/detect_credit_card_numbers_using_luhn_algorithm/
and discovered a problem.

The LUHN algo says that every other number should be doubled, starting with the ones in an _even_ position based on the first number being in _position 1_.

1**2**3**4**5**6**
According to the LUHN algorithm in the above example the ones in bold would be doubled.

But the security essentials Luhn check uses mvexpand which count positions starting with 0 as the first number.
Which leads to that the variables `cce`and `cco` (even and odd I assume) ends up with the numbers switched, according to the SPL in the doc above.

**Comment by josehelps** [comment]
Thank you @kennykentaur for sharing, unfortunately this search is not part of (this) security_content repo, and it is managed specifically by SSE. I will part the message along to that team :+1:
