### ISSUE TITLE
Extract SAM from Registry

### ISSUE THREAD

**Issue by thejanit0r** [splunk/security_content#1634]
Problem description: A false positive is triggered when executing the command "reg save HKCU\Software\Samsung"

Cause: 

Currently the correlation search looks like this:

```
| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time)
  as lastTime from datamodel=Endpoint.Processes where Processes.process_name=reg.exe
  (Processes.process=*save* OR Processes.process=*export*) AND (Processes.process=*sam*
  OR Processes.process=*system* OR Processes.process=*security*) by Processes.dest
  Processes.user Processes.parent_process Processes.process_name Processes.process
  Processes.process_id Processes.parent_process_id | `drop_dm_object_name(Processes)`
  | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)` | `extract_sam_from_registry_filter`
```

the cause of the false positive is due to `Processes.process=*sam*`, which is not specific enough.

A possible solution would be to replace it with `Processes.process="*\sam *"`

Furthermore, the title doesnt really logically match the correlation search because it also triggers when other registry hives are being saved/exported (... `OR Processes.process=*system* OR Processes.process=*security*` ...), for which the same observation about the SAM registry hive also applies. In this case, maybe renaming the use case would be better, e.g. Extraction of Registry Hives, or maybe only make the use case specific to the SAM registry hive.

**Comment by MHaggis** [comment]
Thank you @thejanit0r ! I went ahead and renamed and fixed the `\sam`. We appreciate the feedback!

**Comment by thejanit0r** [comment]
Thanks for the quick response, but your commit still has some issues:

`...AND (Processes.process=*\sam * OR Processes.process=*system* OR Processes.process=*security*)...` 

1. Missing quotes -> should be `Processes.process="*\sam *"`
2. Same problem as for SAM -> should be `OR Processes.process="*\system *" OR Processes.process="*\security *"`
