### ISSUE TITLE
"Join" based only on process_id causes 'collisions'

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#1635]
We found that these 4 CUs are prone to a lot of false positives. 
The two searches are joined via proces_id. The process ID roll over very quickly in big environments so the join is not 'stable'.

Changing these searches so they use process_guid should be straight forward and reduce the FPs a lot.

If you want to take _time also into consideration that commit could be used as an inspiration:
https://github.com/splunk/security_content/commit/7a7341f9bac7a6d9e3404c80ce33b6859de2269e

-Thanks

Relevant CU:
DLLHost with no Command Line Arguments with Network
SearchProtocolHost with no Command Line with Network
GPUpdate with no Command Line Arguments with Network
Rundll32 with no Command Line Arguments with Network

**Comment by MHaggis** [comment]
I have this complete. We're doing some testing right now with the Sysmon TA to ensure things are working correctly.
