### ISSUE TITLE
Create or delete windows shares using net exe

### ISSUE THREAD

**Issue by thejanit0r** [splunk/security_content#1636]
Problem description: False positive are being triggered on commands such as `net localgroup "Share Users"`, `net use \\domain\share`, etc.

Cause:

Currently the correlation search looks like this:

```
| tstats `security_content_summariesonly` count values(Processes.user) as
  user values(Processes.parent_process) as parent_process min(_time) as firstTime
  max(_time) as lastTime from datamodel=Endpoint.Processes where (Processs.process_name=net.exe
  OR Processes.process_name=net1.exe) by Processes.process Processes.process_name
  Processes.dest | `drop_dm_object_name(Processes)` | `security_content_ctime(firstTime)`|
  `security_content_ctime(lastTime)` | search process=*share* | `create_or_delete_windows_shares_using_net_exe_filter` '
```
the cause of the false positive is due to `search process=*share*`, which is way too broad; in fact any command using `net.exe` that just contains the word `share` would trigger an alert.

A possible solution would be to remove the part `search process=*share*` and add the selection directly in the `where` clause, e.g. `where (Processs.process_name=net.exe OR Processes.process_name=net1.exe) AND (Processes.process="* share *")` with space around the word in order to limit false positives.

**Comment by MHaggis** [comment]
Fixed up! Thank you @thejanit0r

**Comment by thejanit0r** [comment]
Hey MHaggis, just noticed that there is a typo aswell, which I didn't notice earlier: `Processs.process_name=net.exe` -> `Processes`

**Comment by MHaggis** [comment]
Fixed again! Thank you @thejanit0r
