### ISSUE TITLE
Access LSASS Memory for Dump Creation not picking up use of Cobalt Strike Mimikatz

### ISSUE THREAD

**Issue by davisshannon** [splunk/security_content#1744]
`sysmon` EventCode=10 TargetImage=*lsass.exe CallTrace=*dbgcore.dll* OR CallTrace=*dbghelp.dll*
  | stats count min(_time) as firstTime max(_time) as lastTime by Computer, TargetImage,
  TargetProcessId, SourceImage, SourceProcessId | rename Computer as dest | `security_content_ctime(firstTime)`|
  `security_content_ctime(lastTime)` | `access_lsass_memory_for_dump_creation_filter`

Doesn't pick up Cobalt Strike Mimikatz use.  Adding in CallTrace=*ntdll.dll* does pick this up though.

**Comment by MHaggis** [comment]
Thank you for this @davisshannon . We created a few new analytics for this and they are out the gate.
