### ISSUE TITLE
ESCU - Windows AdFind Exe - Rule

### ISSUE THREAD

**Issue by annoyingapt** [splunk/security_content#1767]
For rule ESCU - Windows AdFind Exe - Rule, there is no spaces after the arguments in the detection, so -sc will match with -script and -scope etc, either that or include adfind in the process detection. More info on the switches can be found here: https://www.joeware.net/freetools/tools/adfind/usage.htm

Default logic:

`| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes where (Processes.process=*-f* OR Processes.process=*-b*) AND (Processes.process=*objectcategory* OR Processes.process=*-gcb* OR Processes.process=*-sc*) by Processes.dest Processes.user Processes.process_name Processes.process  Processes.parent_process Processes.process_id Processes.parent_process_id | `drop_dm_object_name(Processes)` | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)` | `windows_adfind_exe_filter``

Suggested Logic:

`| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time) as lastTime from datamodel=Endpoint.Processes where (Processes.process=*-f * OR Processes.process=*-b *) AND (Processes.process=*objectcategory* OR Processes.process=*-gcb * OR Processes.process=*-sc *) by Processes.dest Processes.user Processes.process_name Processes.process  Processes.parent_process Processes.process_id Processes.parent_process_id | `drop_dm_object_name(Processes)` | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)` | `windows_adfind_exe_filter``

**Comment by josehelps** [comment]
@annoyingapt Thank you so much :heart: for the heads up and creating an issue, your suggestion makes alot of sense, will get a PR going to make the changes.

**Comment by patel-bhavin** [comment]
fixed and merged : https://github.com/splunk/security_content/pull/1769
