### ISSUE TITLE
Lateral Movement tactic does not render on research.splunk.com

### ISSUE THREAD

**Issue by josehelps** [splunk/security_content#1774]
This was raised by huskersec via splunk user slack. 
![image](https://user-images.githubusercontent.com/1476868/140176936-e13be3e7-1523-4226-a3b0-6c19cfca5ae1.png)

**Comment by patel-bhavin** [comment]
https://github.com/splunk/security_content/pull/1777

**Comment by patel-bhavin** [comment]
https://research.splunk.com/detections/lateral_movement/ 

renders correctly now
