### ISSUE TITLE
Office Application Spawn rundll32 process / Field rename

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#1780]
Hi

Whitelisting for that search is a bit painful because of the field name "values(Processes.process)" 
Would be great if you could rename this to just "process" just like in all other ESCU.

-Thanks

**Comment by tccontre** [comment]
HI mschilt,

thanks for this nice feedback. I'll fix this and update you as soon as possible.

**Comment by tccontre** [comment]
hi @mschilt ,again thanks for your feedback. the minor changes to fix this issue will be in future release. :)

**Comment by tccontre** [comment]
PR for the updated version of this detection was already merged and in queue for release. I'll close now this issue. thanks again
