### ISSUE TITLE
Office Application Drop Executable / join not working?

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#1781]
Hi

This search joins two searches (office process start and exe file creation) by process_guid and _time 
We see strange results of events joined that have a different process GUID/different machine and don't belong to each other.

I think that the join is not working correctly. The field process_guid is not selected in the first tstats (process_id is .. but that's not used) and I doubt that joining based on _time is helpful at all.  A process start and the file creation can differ in minutes/hours..  If office is already open and you double-click on a bad document then sometimes no new process is started with the bad file  (-> DDE .. ) 

Could you please verify that search with your dataset. 

- Thanks.

**Comment by tccontre** [comment]
HI mschilt,

thanks for this great feedback. I'll fix this and update you as soon as possible.

**Comment by tccontre** [comment]
Hi @mschilt ,

again thanks for this great feedback. during testing I confirm that there is some unwanted event catches by the old detection. I fix this and manage to get the only intended event during my testing. :) the changes will be included in future release
![Screenshot 2021-11-09 at 12 52 36](https://user-images.githubusercontent.com/26181693/141322446-52f5325e-324b-4465-bc74-3768a0b140eb.png)
.

**Comment by tccontre** [comment]
PR for the updated version of this detection was already merged and in queue for release. I'll close now this issue. thanks again
