### ISSUE TITLE
Improve description of detection

### ISSUE THREAD

**Issue by josehelps** [splunk/security_content#1784]
https://github.com/splunk/security_content/blob/45ed7cf5643fe0841e98f0a53a1e47edd24ce1eb/detections/endpoint/cmdline_tool_not_executed_in_cmd_shell.yml

this was raised by Stephen Halpin PS Consultant.

**Comment by tccontre** [comment]
thanks for this feedback. will fix this and update you as soon as possible.

**Comment by tccontre** [comment]
description was updated and already merged. updated version will be in future release. kudos to  @MHaggis and @philroyer-phantom for helping me out on this topic.

**Comment by tccontre** [comment]
PR for the updated version of this detection was already merged and in queue for release. I'll close now this issue. thanks again
