### ISSUE TITLE
Create Pass the Ticket/Hash ESCU Detections 

### ISSUE THREAD

**Issue by josehelps** [splunk/security_content#1799]
This request came from https://twitter.com/ateixei, specifically for attacks descriped on this blog:https://stealthbits.com/blog/how-to-detect-pass-the-ticket-attacks/ and also described under lateral movement from this paper: https://dspace.cvut.cz/bitstream/handle/10467/83217/F8-BP-2019-Kotlaba-Lukas-thesis.pdf?sequence=-1&isAllowed=y

**Comment by mvelazc0** [comment]
Created TR-1551 to track this

**Comment by mvelazc0** [comment]
Added detection capabilities on https://github.com/splunk/security_content/pull/2002 and https://github.com/splunk/security_content/pull/2074
