### ISSUE TITLE
issues on ssa delee a net user detection

### ISSUE THREAD

**Issue by josehelps** [splunk/security_content#1831]
https://github.com/splunk/security_content/blob/aefb39a208168b48cc607eac708d5482a89b4b96/detections/endpoint/ssa___delete_a_net_user.yml#L6

* type is incorrect, should be anomaly
* missing observables
* MITRE ID I believe is wrong should be: https://attack.mitre.org/techniques/T1531/
* logic looks like it can be improved since it is only matching on `like(cmd_line, "%/delete%") AND (process_name="net1.exe" OR process_name="net.exe") ` and not any user arguments passed.

**Comment by tccontre** [comment]
thanks for this feedback and suggestion I'll fix and update this issue asap. :)

**Comment by tccontre** [comment]
here is the PR to resolved this issue. it is in review stage now :)
https://github.com/splunk/security_content/pull/1833
