### ISSUE TITLE
Repeated group-by field in "Detect HTML Help Renamed search"

### ISSUE THREAD

**Issue by my2ndhead** [splunk/security_content#1849]
The group-by field `Processes.original_file_name` is repeated. This causes the search to fail.

See [here](https://github.com/splunk/security_content/blob/bee2a4cefa533f286c546cbe6798a0b5dec3e5ef/detections/endpoint/detect_html_help_renamed.yml#L20)

**Comment by MHaggis** [comment]
Thank you @my2ndhead . We'll get this out this week.
