### ISSUE TITLE
Unusual Number of Remote Endpoint Authentication Events / syntax error

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#1904]
Hey

The search misses a pipe between the search and the filter macro.

Its like this:  
.. nd, 1, 0) `unusual_n .. 
but should be this: 
.. nd, 1, 0) | `unusual_n.. 

Thanks

**Comment by mvelazc0** [comment]
Hey Manuel, thanks for catching this !

I submitted a PR (https://github.com/splunk/security_content/pull/1940) to fix thing and will close this issue once merged.
