### ISSUE TITLE
Unusual Number of Remote Endpoint Authentication Events / Feedback

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#1905]
Hi

I really like that idea. 
I am having issues that the DCs and Exchange hosts dominate the list of target hosts in big environments. 

So whitelisting them in an additional filter macro would be great. Something like this: 

`(...)| bucket span=2m _time | stats dc(ComputerName) AS unique_targets values(ComputerName) as target_hosts by _time, Source_Network_Address, Source_Account
| `unusual_number_of_remote_endpoint_authentication_events_targethosts_filter`  
| eventstats  (... )` 

unusual_number_of_remote_endpoint_authentication_events_targethosts_filter = search target_hosts!=DC-* target_hosts!=EXCH-*

What do you think?

**Comment by mvelazc0** [comment]
Hey Manuel, thanks for the feedback!

It makes sense that DCs and Exchange boxes would be triggering this and I agree the solution is to filter out this behavior. I think you have 2 options.

The first one is using the hostnames like you are suggesting. Ideally, the team has defined naming conventions that could help you.

The second option is using IP addresses or IP ranges. Event 4624 has a field that maps to the source IP address.

I'd be curious to know how this works for you. Would you share our slack group channel to talk about it ? 

Invite link: https://join.slack.com/t/splunk-usergroups/shared_invite/zt-yblg8zj4-bImSvLMc_91v6_aYUQ_Kiw
