### ISSUE TITLE
Suspicious Rundll32 Rename / Logic issue & regression

### ISSUE THREAD

**Issue by mschilt** [splunk/security_content#2010]
Hi

The detection "Suspicious Rundll32 Rename" suffers a logic issue (and kind of a regression). 
It looks like this: 
 (a) Processes.process_name=rundll32.exe OR Processes.original_file_name=RUNDLL32.EXE
but it should look like this: 
(b) Processes.original_file_name=RUNDLL32.exe AND Processes.process_name!=rundll32.exe

-> using 'OR' also includes the correctly named Rundll32 which is not intended.

(a) is defined in the macro process_rundll32
(b) Mhaggis tried to fix this in August 2021 with commit https://github.com/splunk/security_content/commit/833001dd15d17bc03ab05c5e30c7361840f283ef unfortunately it looks like this didn't really work out.

Could you please fix the OR -> AND relation. 

Thank you in advance. 
-Manuel

**Comment by mschilt** [comment]
I think the same logic error also applies to most other "Detect renamed .. " alerts. These detections seem to be also affected:  
* Detect mshta renamed 
* Detect Renamed PSExec
* Suspicious MSBuild Rename
* Suspicious microsoft workflow compiler rename
* Detect HTML Help Renamed

**Comment by MHaggis** [comment]
Hi @mschilt,

Thank you for bringing these up. I have slowly been deprecating or converting them to Hunting analytics due to the use of the new process_ macro. Are you finding good use out of these type of analytics? I'm happy to fix them all if you are.
Thank you!
