### ISSUE TITLE
Add NIST Cybersecurity Framework and CIS Control Tags to Research Docs

### ISSUE THREAD

**Issue by drewchurch** [splunk/security_content#2019]
As a user of the research.splunk.com site, I would like to be able to view NIST CSF and CIS Control tags if they are present on a given detection so that I can better find detections that are applicable to my cybersecurity frameworks.

As a user of the research.splunk.com site, I would like to be able to view NIST CSF and CIS Control tags on the Tags page, similar to how ATT&CK/CVEs are shown when present so that I can easily find this content using the Tags page or Search module

**Comment by josehelps** [comment]
solved in https://github.com/splunk/security_content/pull/2142
