### ISSUE TITLE
Add default whitelist to rule Common Ransomware Extensions

### ISSUE THREAD

**Issue by ccl0utier** [splunk/security_content#2053]
The rule **ESCU - Common Ransomware Extensions** triggers false positives from files generated by the **Upgrade Readiness App** (`python_upgrade_readiness_app`).

![image](https://user-images.githubusercontent.com/58239192/156202407-b40e74ca-3779-4248-9c7b-51dcc67e0ff6.png)

![image](https://user-images.githubusercontent.com/58239192/156202674-b14a3f97-8b1b-43fd-a4f8-b4b1d6596be4.png)

Those are generated from the application:

![image](https://user-images.githubusercontent.com/58239192/156202897-d39ece5c-b564-401c-b3e7-d7b5f084539b.png)

We could exclude them automatically through the `common_ransomware_extensions_filter` macro.  For example: 
`NOT (file_name IN("jura_entry.lock", "pura_entry.lock") file_path="*/etc/apps/python_upgrade_readiness_app/local")`.

**Comment by ljstella** [comment]
This has been fixed in #2054 and will ship in the next tagged release.
