### ISSUE TITLE
Cloud detection - aws_createaccesskey.yml - Incorrect search

### ISSUE THREAD

**Issue by EadesCloudDef** [splunk/security_content#2062]
The search as is won't do much. 

By design "| search userIdentity.userName!=requestParameters.userName" won't actually check if the contents of each field are not equal, or for that matter, equal.

To do this correctly, replace the line with the following:
| eval match=if(match(userIdentity.userName,requestParameters.userName),0,1) 
| search match=0

This will evaluate if the two fields values are equal or not, and then search for where they are not equal.

**Comment by patel-bhavin** [comment]
that makes sense! thank you reporting the issue. we will update this search

**Comment by patel-bhavin** [comment]
https://github.com/splunk/security_content/pull/2065

**Comment by patel-bhavin** [comment]
we should look for events when the fields do not match, updated the eval condition accordingly to: 

| eval match=if(match(userIdentity.userName,requestParameters.userName),1,0)
| search match=0

**Comment by patel-bhavin** [comment]
PR iss merged!
