### ISSUE TITLE
Detect Regasm with no Command Line Arguments

### ISSUE THREAD

**Issue by thejanit0r** [splunk/security_content#2066]
**Problem**: regexes are case sensitive, therefore the search query for this use case doesn't always provide the expected results (e.g. if called as RegAsm.exe)

```
search: '| tstats `security_content_summariesonly` count FROM datamodel=Endpoint.Processes
  where `process_regasm` by _time span=1h  Processes.process_id Processes.process_name
  Processes.dest Processes.process_path Processes.process Processes.parent_process_name
  | `drop_dm_object_name(Processes)` | `security_content_ctime(firstTime)` | `security_content_ctime(lastTime)`
  | regex process="(regasm\.exe.{0,4}$)" | `detect_regasm_with_no_command_line_arguments_filter`'
```

**Proposed solution**: replace `regex process="(regasm\.exe.{0,4}$)"` with `regex process="(?i)(regasm\.exe.{0,4}$)"`

Link: https://github.com/splunk/security_content/blob/develop/detections/endpoint/detect_regasm_with_no_command_line_arguments.yml

**Comment by MHaggis** [comment]
Hi @thejanit0r , we got these updated and merged a little bit back. Let us know if you run into any we missed or any other issues.
