### ISSUE TITLE
"ESCU - Excessive number of distinct processes created in Windows Temp folder - Rule" too long to save

### ISSUE THREAD

**Issue by alee-splunk** [splunk/security_content#2070]
In ES, trying to save anything related to the "ESCU - Excessive number of distinct processes created in Windows Temp folder - Rule" search results in an error "There was an error saving the correlation search: Search name is too long." 

Steps to repo:
1. Go to Content Manager in ES and search for "ESCU - Excessive number of distinct processes created in Windows Temp folder - Rule" and edit the search
2. Click save and it will result in the error message

**Comment by patel-bhavin** [comment]
https://github.com/splunk/security_content/pull/2085/files
