### ISSUE TITLE
"Windows Event for Service Disabled" - Update needed. 

### ISSUE THREAD

**Issue by patel-bhavin** [splunk/security_content#2078]
![image](https://user-images.githubusercontent.com/7771446/157765811-427d0099-9875-43a5-b1aa-fe34fad16183.png)

**Comment by tccontre** [comment]
Ill take a look on this. ;)

**Comment by tccontre** [comment]
this is the PR for including the name of the service that was got disabled. the field added is the service and service_name that contain the service that got disabled that i think mapped from param4 field.
https://github.com/splunk/security_content/pull/2144

**Comment by tccontre** [comment]
this fix is already merged. closing this issue
