### ISSUE TITLE
TR-2295: "Windows Kerberos Local Successful Logon" Detection SPL

### ISSUE THREAD

**Issue by sahoo8920** [splunk/security_content#2212]
Splunk research says: "The target user security identified will be set to the built-in local Administrator account, along with the remote address as localhost - 127.0.0.1."

Local admin account SID is something like "SID S-1-5-domain-500". Can we please add the following two key-value in the SPL to filter out FP:

Security_ID=S-1-5-*-500 AND Account_Name=Administrator

**Comment by MHaggis** [comment]
Hi @sahoo8920 ,
Apologies for the delay. Are you able to share some of the false positives? 
From what we understand is that the way the UF works is it will perform a reverse lookup of the security_ID to username and it is one or the other.
