### ISSUE TITLE
content_ctl.py not updating coverage.csv

### ISSUE THREAD

**Issue by patel-bhavin** [splunk/security_content#2215]
this file needs to be updated while generating docs: https://github.com/splunk/security_content/blob/develop/docs/mitre-map/coverage.csv

The original code : https://github.com/splunk/security_content/blob/v3.33.0/bin/generate-coverage-map.py

**Comment by P4T12ICK** [comment]
contentctl reporting is updating this file. The command is:
python3 contentctl.py -p . reporting

I think the problem why it's not updated through CI/CD is that it is missing in the Github Actions job update-sources-github.

I will fix it.

**Comment by patel-bhavin** [comment]
Closing this Issue, the PR was merged! : https://github.com/splunk/security_content/pull/2224
