### ISSUE TITLE
Hosts receiving high volume of network traffic from email server time frame

### ISSUE THREAD

**Issue by jwindley-splunk** [splunk/security_content#2226]
Hi, looking at this search I think it should be running over a longer time period than just 60 minutes. In my view, it would more likely need to run over 30 days to build the proper baseline.

**Comment by josehelps** [comment]
hey this is a experimental detection https://research.splunk.com/network/hosts_receiving_high_volume_of_network_traffic_from_email_server/ .. so we really did not configure it. With that said I started a PR to create a deployment for this detection that goes back to 30 days. I do not think this will have the intended effect until we make some code changes in our tooling to apply deployments to experimental detections. 

https://github.com/splunk/security_content/tree/issue_2226

CC @P4T12ICK
