### ISSUE TITLE
ESCU - Detect Unauthorized Assets by MAC address - Rule should use dest_ip not src_ip and signature needs updated

### ISSUE THREAD

**Issue by woody188** [splunk/security_content#2235]
| tstats `security_content_summariesonly` count from datamodel=Network_Sessions where nodename=All_Sessions.DHCP All_Sessions.signature=DHCPREQUEST by All_Sessions.src_ip All_Sessions.dest_mac 
| dedup All_Sessions.dest_mac 
| `drop_dm_object_name("Network_Sessions")` 
| `drop_dm_object_name("All_Sessions")` 
| search NOT 
    [| inputlookup asset_lookup_by_str 
    | rename mac as dest_mac 
    | fields + dest_mac] 
| `detect_unauthorized_assets_by_mac_address_filter`

The team corrected dest_mac in 2021 but did not address All_Sessions.src_ip at the same time. Both should have been switched to use dest_ per the CIM Network Sessions model.

dest_ip = The internal IP address allocated to the client initializing a network session.

For DHCP and VPN events, this is the IP address leased to the client.

src_ip = The IP address of the client initializing a network session.

Not applicable for DHCP events.

Also .signature=DHCPREQUEST doesn't really exist. These are the signatures from the Splunk_TA_windows:

DNS dynamic update request
A lease was renewed by a client
DNS dynamic update successful
DNS dynamic update failed
A lease was denied
A new IP address was leased to a client
A lease was released by a client
A lease was expired
A lease was deleted
An IP address was found to be in use on the network

I switched it to use All_Sessions.tag=dhcp instead.

Have to wonder if people are just happy getting no results? :)

This is the full SPL I'm currently using for Windows based DHCP environment (NOTE: Github removes the "tick" marks):

| tstats `security_content_summariesonly` count from datamodel=Network_Sessions where nodename=All_Sessions.DHCP All_Sessions.tag=dhcp by All_Sessions.dest_ip All_Sessions.dest_mac
| dedup All_Sessions.dest_mac 
| `drop_dm_object_name("Network_Sessions")` 
| `drop_dm_object_name("All_Sessions")` 
| search NOT 
    [| inputlookup asset_lookup_by_str 
    | rename mac as dest_mac 
    | fields + dest_mac] 
| `detect_unauthorized_assets_by_mac_address_filter`

**Comment by ljstella** [comment]
Went ahead and merged this update in #2248 to the experimental search.
