### ISSUE TITLE
Saved Search "ESCU - Rundll32 LockWorkStation - Response Task" refers to missing macro "rundll32_lockworkstation_filter"

### ISSUE THREAD

**Issue by ccl0utier** [splunk/security_content#2253]
Symptoms:

![image](https://user-images.githubusercontent.com/58239192/174805054-9076037c-d162-4bcf-8679-2c828b168b3d.png)

This seems to be caused by the `ESCU - Rundll32 LockWorkStation - Response Task` saved search in ESCU referencing the macro `rundll32_lockworkstation_filter` which is not present in `macros.conf`.

![image](https://user-images.githubusercontent.com/58239192/174805351-8152c246-3318-4c08-9f69-dbd07a06b5c3.png)

**Comment by ljstella** [comment]
This should be resolved in 3.44.0. This search was mistakenly classified as a Response Task, which doesn't normally have a filter macro. Its been adjusted to an Anomaly for the next release.
