### ISSUE TITLE
Deprecated Detections not showing a warning on research.splunk.com

### ISSUE THREAD

**Issue by josehelps** [splunk/security_content#2256]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1476868/174881486-7b2edc90-f4dd-41f6-897b-6baa1a55ac3e.png">
 
Should pop a warning letting customers know it is deprecated just like the ESCU page.

**Comment by patel-bhavin** [comment]
this search doesnt exist in our repo and deprecated detections show a warning as of 3.52.0
