### ISSUE TITLE
Issue with the join, search does not return `process_guid`

### ISSUE THREAD

**Issue by josehelps** [splunk/security_content#2272]
https://github.com/splunk/security_content/blob/aeceacc7378e501c4fd3b01816e1d6dc1e34de8c/detections/endpoint/suspicious_image_creation_in_appdata_folder.yml#L17

Originally reported in user slack: https://splunk-usergroups.slack.com/archives/C78NT6CQ7/p1657125989870159

**Comment by tccontre** [comment]
thank you @d1vious Im on it now

**Comment by tccontre** [comment]
the fix for this issue is in this PR:
https://github.com/splunk/security_content/pull/2274
