### ISSUE TITLE
Renaming off a CIM compliant field to a custom one

### ISSUE THREAD

**Issue by TheLawsOfChaos** [splunk/security_content#2281]
https://github.com/splunk/security_content/blob/aeceacc7378e501c4fd3b01816e1d6dc1e34de8c/detections/endpoint/registry_keys_used_for_persistence.yml#L29
https://github.com/splunk/security_content/blob/aeceacc7378e501c4fd3b01816e1d6dc1e34de8c/detections/endpoint/registry_keys_used_for_persistence.yml#L32-L33

Renaming in both searches `process_guid` to `proc_guid`, when `process_guid` is the CIM compliant field. Should just remove both rename lines.

This is probably done in _many_ correlation searches and analysis will need to be done to determine how many of them do this, to have them fixed.

**Comment by josehelps** [comment]
@TheLawsOfChaos Thank you for opening this one, we will take a peak, we been considering restructuring how we approach join searches since they do have a few issues (limit result set on joins returned).

**Comment by TheLawsOfChaos** [comment]
@d1vious think you meant that (and the 3.46.0 tag) for https://github.com/splunk/security_content/issues/2280

**Comment by josehelps** [comment]
I did thank :smile: closing!
