### ISSUE TITLE
Custom app functionality not available "init" missing from contentctl.py

### ISSUE THREAD

**Issue by musmansaleem** [splunk/security_content#2306]
Hi i was looking to use the custom app functionality to build the custom CI/CD pipeline as shown in the .conf 22 session. But when you try running contentctl.py with "init" it does not support it, even the --help does not show the options that were shown in the .conf session. i am looking to use it for my on premise setup not splunk cloud so wont have acs in it. if it somewhere checks for acs generated config thats not something which i have, so would suggest removing that dependency if its there.
![image (2)](https://user-images.githubusercontent.com/58958495/181420126-0d8cc571-a05e-433b-87ae-cc8ab2aecb5d.png)

![image (4)](https://user-images.githubusercontent.com/58958495/181420319-a86f090a-3f04-4aad-9f65-0703c2519f86.png)

**Comment by musmansaleem** [comment]
I having been searching through code, seems like that version of contentctl.py probably is not published for splunk clients/community.

**Comment by pyth0n1c** [comment]
Hi everyone!  Sorry that this was not yet available.  We had this in a separate branch and were making some improvements.  Those changes have been merged 4 days ago (August 12) as part of the following PR:
[https://github.com/splunk/security_content/pull/2316](https://github.com/splunk/security_content/pull/2316) 
Please let us know if you have any more questions!

**Comment by pyth0n1c** [comment]
Since there have been no other comments on this, I am going to close it as completed.  Please feel free to re-open if there are other issues.
