### ISSUE TITLE
short_lived_windows_accounts.yml adding risk to user

### ISSUE THREAD

**Issue by jwindley-splunk** [splunk/security_content#2353]
Can we not get the 'src_user' (from the Account Management dataset) in the results of the search? This would be more useful to add risk to rather than the target user account name that was created/deleted

**Comment by josehelps** [comment]
Hey @jwindley-splunk mind pointing me back to specific searches/detections you had in mind for this issue?

**Comment by patel-bhavin** [comment]
@jwindley-splunk : Hello Jamie! thanks for the suggested on getting that field name from account management dataset:

I have updated and tested this search and will ship this update shortly:

![image](https://github.com/user-attachments/assets/347a2f50-e242-4349-ab56-05dab8c18fe9)

**Comment by patel-bhavin** [comment]
PR - https://github.com/splunk/security_content/pull/3208. We will ship this in the next ESCU release! Thank you @jwindley-splunk
