### ISSUE TITLE
O365 Disable MFA not showing target user

### ISSUE THREAD

**Issue by jwindley-splunk** [splunk/security_content#2355]
Description of this use case is "This search detects when multi factor authentication has been disabled, what entitiy performed the action and against what user"

But, the results don't show the target user. I don't know for certain, but I expect you also need to include the 'object' field in the search results

**Comment by jwindley** [comment]
https://github.com/splunk/security_content/pull/2441

**Comment by patel-bhavin** [comment]
Fixed this in https://github.com/splunk/security_content/pull/2443. Thank you for reporting this bug!
