### ISSUE TITLE
Windows Events for Certificate Exports

### ISSUE THREAD

**Issue by inthecards77** [splunk/security_content#2378]
I like to track these to look for possible impersonation threat.

Log Name: Microsoft-Windows-CertificateServicesClient-Lifecycle-User/Operational
Source: Microsoft-Windows-CertificateServicesClient-Lifecycle-User
Date: 6/17/2022 12:32:49 PM
Event ID: 1007
Task Category: None
Level: Information
Keywords:
User: HP-AR\inthe
Computer: HP-AR
Description:
A certificate has been exported. Please refer to the &quot;Details&quot; section for more information.

Log Name: Microsoft-Windows-CertificateServicesClient-Lifecycle-System/Operational
Source: Microsoft-Windows-CertificateServicesClient-Lifecycle-System
Date: 6/18/2022 7:53:18 AM
Event ID: 1007
Task Category: None
Level: Information
Keywords:
User: HP-AR\inthe
Computer: HP-AR
Description:
A certificate has been exported. Please refer to the &quot;Details&quot; section for more information.

**Comment by MHaggis** [comment]
Hi @inthecards77 , Thank you for the share. Would you mind sharing a bit more details of the attack or a blog post related? Thank you

**Comment by inthecards77** [comment]
Hi, sure thing.

I have exported user and system authentication certificates from Windows
machines to conduct impersonation attacks.

Steps:
1. get access to machine
2. get machine name/user name/password
3. export certificates and private keys
4. install certificates on new Windows VM with same machine name and user
name
5. connect to SSL VPN, Wireless Networks with 802.1x, etc as the user.

This can also be used against signing certificates to spoof mail from
another machine or sign code. Same windows event for any certificates
exported.

Let me know if you need more info.

Alan

**Comment by MHaggis** [comment]
Thank you for this! I dug in on this topic and shipped a good amount of content around certificate services. Thank you!
