### ISSUE TITLE
blog's error

### ISSUE THREAD

**Issue by FANGOD** [splunk/security_content#2381]
Sorry I didn't see any way to feedback on the blog.

Please check the wrong SHA256 in this blog.

https://www.splunk.com/en_us/blog/security/threat-update-acidrain-wiper.html

![image](https://user-images.githubusercontent.com/21952721/191697643-60459a5c-46f1-4c43-8ecf-499edae0cd45.png)

**Comment by tccontre** [comment]
Hi, as far as I checked the sha256 the hash is correct.
https://www.virustotal.com/gui/file/9b4dfaca873961174ba935fddaf696145afe7bbf5734509f95feb54f3584fd9a/community

and also other blog used this hash for analyzing this acidrain
https://www.trustwave.com/en-us/resources/blogs/spiderlabs-blog/overview-of-the-cyber-weapons-used-in-the-ukraine-russia-war/

**Comment by tccontre** [comment]
Thanks again for this feedback. I will close now this issue.
