### ISSUE TITLE
Experimental Detection "Exchange PowerShell Module Usage" fails due to a syntax error

### ISSUE THREAD

**Issue by ccl0utier** [splunk/security_content#2396]
The rule as currently written won't work... it has duplicate by clauses.

![image](https://user-images.githubusercontent.com/58239192/193335911-5f11fba8-733c-47b0-b86c-21c4bbb7d10b.png)

**Comment by MHaggis** [comment]
Thank you! Got it on this next release.

**Comment by MHaggis** [comment]
Fixed! Thank you
