### ISSUE TITLE
Experimental Detection "Exchange PowerShell Abuse via SSRF" fails due to a syntax error

### ISSUE THREAD

**Issue by ccl0utier** [splunk/security_content#2397]
The rule has an extra unnecessary pipe character at the beginning of its search causing an error.

![image](https://user-images.githubusercontent.com/58239192/193336352-45a0512e-7a65-461c-a17b-20d0c4997fe8.png)

**Comment by MHaggis** [comment]
Good catch! Thank you!

**Comment by MHaggis** [comment]
Fixed! Thank you
