### ISSUE TITLE
Exprimental Detection "Splunk Account Discovery Drilldown Dashboard Disclosure" fails due to missing lookup

### ISSUE THREAD

**Issue by ccl0utier** [splunk/security_content#2398]
[Splunk Account Discovery Drilldown Dashboard Disclosure](https://splunkresearch.com/application/f844c3f6-fd99-43a2-ba24-93e35fe84be6/)

![image](https://user-images.githubusercontent.com/58239192/193337128-d696a7d0-1f93-43dc-bfef-65ce4bb3ed49.png)

**Comment by ljstella** [comment]
Merged a fix in #2403
