### ISSUE TITLE
Experimental Detection "Remote Desktop Network Traffic" False Positives

### ISSUE THREAD

**Issue by ccl0utier** [splunk/security_content#2402]
Rule [Remote Desktop Network Traffic](https://splunkresearch.com/network/272b8407-842d-4b3d-bead-a704584003d3/) should be updated to disregard "blocked" traffic (e.g.: add `... AND All_Traffic.action = "allowed"`) to prevent false positives.

**Comment by ljstella** [comment]
Merged a fix in #2403
