### ISSUE TITLE
[BUG] Common Ransomware Extensions - Lack of Fidelity 

### ISSUE THREAD

**Issue by nterl0k** [splunk/security_content#2448]
### **Describe the bug**
Correlation is somewhat noisy in a production environment. 

Found that refactoring SPL results with better accuracy. Added additional logic to align correlation with false positive description text "If this is a true ransomware attack, there will be a large number of files created with these extensions" - which is typically true of ransomware behavior

Made the following changes:

1. Refactored SPL to add extra context and align correlation with use case.
2. Added an extraction (true_file_path) for file path without leaf/file included
3. Add stats on # of files and # of paths present per destination/device
4. Use where statement to reduce noise potential of correlation with respect to "true" ransomware behavior (multiple files/paths impacted)

```
| tstats `security_content_summariesonly` min(_time) as firstTime max(_time) as lastTime count latest(Filesystem.user) as user values(Filesystem.file_path) as file_path from datamodel=Endpoint.Filesystem by Filesystem.file_name Filesystem.dest _time span=1h
| `drop_dm_object_name(Filesystem)` 
| rex field=file_name "(?<file_extension>\.[^\.]+)$" 
| rex field=file_path "(?<true_file_path>([^\\\]*\\\)*).*" 
| stats min(firstTime) as firstTime max(lastTime) as lastTime latest(user) as user dc(true_file_path) as path_count dc(file_name) as file_count latest(file_name) as file_name latest(true_file_path) as file_path by dest file_extension
| `security_content_ctime(lastTime)` 
| `security_content_ctime(firstTime)`
| `ransomware_extensions`
| where path_count > 1 OR file_count > 20
| `common_ransomware_extensions_filter`

```

### **Expected behavior**
Higher fidelity alerting with regards to potential ransomware infection.

### **Screenshots**
![Snipaste_2022-11-10_09-25-41](https://user-images.githubusercontent.com/38897662/201140118-f6fefc21-0940-44dd-8517-125330b16596.png)

### **App Version:**
 - ESCU: [e.g. 3.3.1]

### **Additional context**
Original Search: This search has completed and has returned 414 results by scanning 36,544,886 events in 38.897 seconds
Modified Search: This search has completed and has returned 3 results by scanning 36,591,795 events in 38.664 seconds

**Comment by MHaggis** [comment]
Thank you for the feedback on this. I agree with the changes and will work this into the next release!

**Comment by MHaggis** [comment]
![image](https://user-images.githubusercontent.com/5632822/201180265-a384bb26-d8e2-47ae-a52a-2713c1a0feb3.png)

**Comment by nterl0k** [comment]
Great!

This notable description helps contextualize what doesn't show up in incident review.

The device `$dest$` wrote `$file_count$` files to `$path_count$` path(s) with the `$file_extension|s$` extension. This extension and behavior may indicate a `$Name$` ransomware attack.

**Comment by MHaggis** [comment]
Yes - I like that description a lot more! Apologies for missing that on this release. I'll get it out on the next.

**Comment by MHaggis** [comment]
Hey @nterl0k  Where are you pulling the $Name$ field from?

**Comment by nterl0k** [comment]
The 'ransomware_extensions' macro as part of a lookup.

**Comment by patel-bhavin** [comment]
merged!
