### ISSUE TITLE
[BUG] Batch File Write to System32

### ISSUE THREAD

**Issue by nterl0k** [splunk/security_content#2451]
### **Describe the bug**
Correlation incorrectly joins or doesn't identify relevant fields due to lack of "Processes.process_guid" in search and lack of "Filesystem.process_guid" in sub-search. Also using the "_time" field as a sub-search join is mostly superfluous with the Sysmon process_guid field. Process_guid is created by Sysmon using the process create time as part of it's it's guid construction. 

### **Expected behavior**
Process and File create should be linked via "process_guid" to correctly correlate Sysmon events. Attached updated correlation logic to correct issue, which also improves search performance. 

```
| tstats `security_content_summariesonly` count FROM datamodel=Endpoint.Processes where Processes.process_name=* by _time span=1h Processes.process_guid Processes.process_name Processes.dest Processes.user 
| `drop_dm_object_name(Processes)` 
| join process_guid 
    [| tstats `security_content_summariesonly` count min(_time) as firstTime max(_time) as lastTime FROM datamodel=Endpoint.Filesystem where Filesystem.file_path IN ("*\\system32\\*", "*\\syswow64\\*") Filesystem.file_name="*.bat" by _time span=1h Filesystem.dest Filesystem.file_create_time Filesystem.file_name Filesystem.file_path Filesystem.process_guid 
    | `drop_dm_object_name(Filesystem)`]
| table dest user file_create_time, file_name, file_path, process_name, firstTime, lastTime 
| dedup file_create_time
| `security_content_ctime(firstTime)` 
| `security_content_ctime(lastTime)`
| `batch_file_write_to_system32_filter`
```

Will need to update required fields to
_time
Filesystem.dest
Filesystem.file_name
Filesystem.user
Filesystem.file_path
Filesystem.process_guid
Processes.process_guid
Processes.process_name
Processes.dest

### **Screenshots**
Original Search
![Snipaste_2022-11-11_09-16-27](https://user-images.githubusercontent.com/38897662/201360152-e86f6de3-00a9-48e4-b6be-c8a4553b1673.png)

Modified Search
![Snipaste_2022-11-11_09-25-05](https://user-images.githubusercontent.com/38897662/201360673-889b5a25-1d0a-4ea9-8a26-9beb2bbf6ac9.png)

### **App Version:**
 - ESCU: [e.g. 3.3.1]

### **Additional context**
Original Search: This search has completed and has returned 1 results by scanning 5,893,423 events in 49.042 seconds
Modified Search:  This search has completed and has returned 1 results by scanning 5,893,423 events in 30.48 seconds

Sysmon process guid structure info
https://learn.microsoft.com/en-us/answers/questions/234884/structure-of-process-guids-used-in-sysmon-etw-even.html
https://gist.github.com/mattifestation/0102042160c9a60b2b847378c0ef70b4

**Comment by patel-bhavin** [comment]
@nterl0k :Amazing feedback! we updated the search in this PR : https://github.com/splunk/security_content/pull/2487
