### ISSUE TITLE
On Prem Splunk Automated Deployments

### ISSUE THREAD

**Issue by seanludo** [splunk/security_content#2484]
- I notice after reading through your documentation you have the following command:

`cloud_deploy - Using ACS, deploy your custom app to a running Splunk Cloud Instance.`

- Is it possible to deploy to an on prem version of splunk or are there any plans to add this as a feature in future for those who do not use splunk cloud ?=
- I did see that Eric Mcginnis mentioned it in the conf video SEC1197C that deployments of the generates app are possible on prem but is this manual only ?

Thankyou

**Comment by P4T12ICK** [comment]
We are working on this feature in our new contenctl tooling.
https://github.com/splunk/contentctl
