### ISSUE TITLE
[BUG] Trying to install v3.58.0 in ES after automated update prompt results in HTTP 500

### ISSUE THREAD

**Issue by ccl0utier** [splunk/security_content#2543]
## Issue Description

Logging into an ES instance that does not have v3.58.0 installed yet will ask the user to update ESCU.  When trying to do so, an HTTP 500 error will occur and prevent installation.

![image](https://user-images.githubusercontent.com/58239192/219377798-6537f116-5ea0-46e8-9e52-1303a050b1d6.png)

![image](https://user-images.githubusercontent.com/58239192/219377104-b3ea0132-1e7b-4392-8c99-d7c1259db54d.png)

Installation can still be done manually with success on Splunk Enterprise (install app from file -> upgrade) but not on Splunk Cloud.  (using Find more apps -> Update also yields a HTTP 500 error).

I've reproduced this on 2 separate instances.

**Comment by ljstella** [comment]
Spoke to @ccl0utier offline, this is an existing known-issue w/ Splunkbase.
