### ISSUE TITLE
[BUG] Potential mistake in "Splunk User Enumeration Attempt"

### ISSUE THREAD

**Issue by iso-rgomez** [splunk/security_content#2563]
Query as written:

 `splunkd_failed_auths` 
| stats count(user) as auths by user, src 
| where auths>5 
| stats values(user) as "Users", sum(auths) as TotalFailedAuths by src 
| `splunk_user_enumeration_attempt_filter`

The "count" on the second line may have been intended to be "dc".  As implemented/written, this rule just checks for a cluster of 5 or more failed authentications from any number of users, and I suspect the intention was to check for a cluster of failed authentications for 5 or more users.

**Comment by patel-bhavin** [comment]
Thanks for reporting this! Updated this search : https://github.com/splunk/security_content/pull/2798
