### ISSUE TITLE
[BUG] "DNS Query Length With High Standard Deviation" not setting risk score correctly

### ISSUE THREAD

**Issue by iso-rgomez** [splunk/security_content#2568]
### **Describe the bug**
This rule configuration, by default, generates a Risk Score for the Risk Object Field "host".  However, this query does not include a field "host" in its output.

### **Expected behavior**
A field host should exist in the query output (likely originally intended to be the host requesting the DNS record)

### **App Version:**
 - ESCU: 3.61.0
 - Splunk Security Essentials: 3.7.0

**Comment by patel-bhavin** [comment]
updated the search to have host in the output!
