### ISSUE TITLE
[BUG] (False Positive) SVD-2023-0211 Search "Improperly Formatted INGEST_EVAL" Alerts on Itself

### ISSUE THREAD

**Issue by arcsector** [splunk/security_content#2572]
### **Describe the bug**
Upon running the [search for SVD-2023-0211](../blob/develop/detections/application/splunk_improperly_formatted_parameter_crashes_splunkd.yml), twice, the search shows itself being run in the results, resulting in a false positive every time the search is ran.

### **Expected behavior**
The search should blacklist any search that uses the search criteria it's looking for, specifically I would recommend adding `Search_Activity.search!="*splunk_improperly_formatted_parameter_crashes_splunkd_filter*"` to the `WHERE` clause.

### **App Version:**
 - ESCU: 3.60.0
 - Splunk Security Essentials: 3.7.0

**Comment by rosplk** [comment]
This was fixed and merged https://github.com/splunk/security_content/commit/4d2e635a5930c7120a0032dccb4f1b56db3af1b8

**Comment by arcsector** [comment]
Awesome - thanks.
