### ISSUE TITLE
[BUG] ESCU - Prohibited Software On Endpoint - Rule 

### ISSUE THREAD

**Issue by ccl0utier** [splunk/security_content#2624]
Rule `ESCU - Prohibited Software On Endpoint - Rule` fails to run with the following error:

![image](https://user-images.githubusercontent.com/58239192/232595338-4f98f7da-7344-49bf-868c-18e36b531784.png)

Since this rule is deprecated, maybe we should remove it?

**Comment by ljstella** [comment]
Thanks for opening this issue. We're already tracking this issue. Unfortunately, removing a detection is not possible at this time.

**Comment by ccl0utier** [comment]
Noted Lou, thanks!
