### ISSUE TITLE
[BUG] Azure AD Authentication Failed During MFA Challenge - Rename userPrincipalName field

### ISSUE THREAD

**Issue by cp-sn** [splunk/security_content#2685]
### **Describe the bug**
In the SC "ESCU - Azure AD Authentication Failed During MFA Challenge - Rule" the field "values(userPrincipalName)" needs to be rename to match the field names use in "Identity Extraction" and "Risk Object Field".

**Comment by patel-bhavin** [comment]
Thank you @cp-sn : we have updated search to output userPrincipalName
