### ISSUE TITLE
[BUG] Unable to overwrite default lookup with custom lookup in macro dynamic_dns_providers

### ISSUE THREAD

**Issue by vvlier** [splunk/security_content#2709]
The detection "_Detect hosts connecting to dynamic domain providers_" use the macro _dynamic_dns_providers_ to check lookups 
dynamic_dns_providers_default.csv and dynamic_dns_providers_local.csv for dynamic dns domains.

The macro put the highest priority on the result from the default lookup before the local lookup. So if you unfortunately match the default lookup, you cannot overwrite the result with the local lookup.

For instance, we have query like **_xxx.i.02.cls.sophosxl.net_** from the Sophos Live Protection that matches **_\*.02.cl\*_** from the default lookup and is seen as a dynamic DNS host. If you add a rule specific to **_\*.sophosxl.net\*_** in the local lookup with isDynDNS_local set to false, it does not change the detection result.

To be able to put local exception, instead of:
```
| eval isDynDNS = coalesce(isDynDNS_default,
  isDynDNS_local)
```
the macro should do it in the reverse order:
```
| eval isDynDNS = coalesce(isDynDNS_local,
  isDynDNS_default)
```

**Comment by josehelps** [comment]
@vvlier created a PR given your feedback, thank you so much sorry this took a while to get to: https://github.com/splunk/security_content/pull/2947
