### ISSUE TITLE
Improve performance of pretrained DGA model

### ISSUE THREAD

**Issue by dglauche** [splunk/security_content#2744]
The provided notebook has a logic flaw which results in time consuming unnecessary operations

I improved the code so that running it on thousand domains takes seconds not minutes: [link](https://github.com/splunk/security_content/compare/develop...dglauche:security_content:develop)

**Comment by patel-bhavin** [comment]
@ksharad-splunk is taking a look at testing your proposed fix! Thank you @dglauche! nice hanging out at .conf

**Comment by patel-bhavin** [comment]
The code has been tested and merged! Thank you @dglauche!
