### ISSUE TITLE
[BUG] Splunk Attack Analyzer Input Playbok

### ISSUE THREAD

**Issue by kelby-shelton** [splunk/security_content#2755]
### **Describe the bug**
In the Splunk Attack Analyzer Input playbook, there is a flaw in the logic in the normalize_url and normalize_file blocks. Occasionally, when multiple inputs are provided, the detonation ID and the get job ID lists will be out of order. This causes the IF statement, `orig_job == filtered_job` to never succeed, and thus the dictionary to never get populated. This causes a KEY error in when trying to access the URL or File associated with the job dictionary, a few lines down.

### **Expected behavior**
The playbook runs without error.

### **App Version:**
N/A

### **Additional context**
Recommended fix:

Change:
```    
for orig_url, orig_job, filtered_job in zip(filtered_result_0_parameter_file, filtered_result_0_data___jobid, filtered_result_1_parameter_job_id):
        if orig_job == filtered_job:
            job_file_dict[filtered_job] = orig_url
```
to:
```
    for orig_url, orig_job in zip(filtered_result_0_parameter_file, filtered_result_0_data___jobid):
        for filtered_job in filtered_result_0_data___jobid:
            if orig_job == filtered_job:
                job_file_dict[filtered_job] = orig_url
```
This needs to be changed in both the normalize_url and normalize_file blocks.

**Comment by tccontre** [comment]
this is the PR for the fix:
https://github.com/splunk/security_content/pull/2756/files

tested
