### ISSUE TITLE
[BUG] Broken link and missing instructions for producing MITRE Navigator map

### ISSUE THREAD

**Issue by alexhaydock** [splunk/security_content#2757]
### **Describe the bug**
The link to `generate-coverage-map.py` in the README.md is broken, as the structure of the MITRE Navigator map generation code seems to have been updated since the README was created.

https://github.com/splunk/security_content/blob/cf343e9e2afa08a56ac1516c0efeea1bb84078ce/README.md?plain=1#L101

Similarly, documentation on how to the script works produce a MITRE Navigator coverage map from the detection content is missing. This would be particularly useful when dealing with a repo of forked/modified content.

### **Expected behavior**
The README should link to the correct script/documentation for the code within this repository which builds the MITRE Navigator map from the detection content.

**Comment by josehelps** [comment]
@alexhaydock you are absolutely correct, much of this tooling was moved to another repo, we need to come back and update the README.md here, but if you are still curious how to do this checkout: https://github.com/splunk/contentctl?tab=readme-ov-file#contentctl-report
