### ISSUE TITLE
When trying to build attack range I get the following error 'No module named 'azure.mgmt.resource'[BUG]

### ISSUE THREAD

**Issue by Cybertooth34** [splunk/security_content#2762]
When I run the following command:
python3 attack_range.py build 

I get the following error:
attack_range/modules/azure_service.py", line 3, in <module>
    from azure.mgmt.resource import ResourceManagementClient
ModuleNotFoundError: No module named 'azure.mgmt.resource'

My question is, why am I seeing this error when I am building the attack range locally on my machine

I wouldn't expect to any errors related to azure or aws if I am running the attacks locally

Any help is much appreciated!!!

**Comment by patel-bhavin** [comment]
@Cybertooth34 : if you are running the range locally, you would still need all the dependencies installed in your poetry. This seems like a local environment issue. Open this issue on the attack_range repository if the issue still persists after installing the dependencies using poetry?  
https://github.com/splunk/attack_range
