### ISSUE TITLE
[BUG] Active_Directory_Disable_Account_Dispatch

### ISSUE THREAD

**Issue by kelby-shelton** [splunk/security_content#2769]
### **Describe the bug**
There are two bugs:
The playbook has a decision block called "observable output filter" which is not functioning as a filter.
The playbook has a decision block at the beginning called "username filter" which is not functioning as a filter and it is checking for a field called "act" which does not appear to be relevant to the playbook.

### **Expected behavior**
A filter block would follow the decision block and all downstream blocks would use the filtered block.

### **Screenshots**
Existing structure:
![Screenshot 2023-07-13 at 2 18 24 PM](https://github.com/splunk/security_content/assets/69353980/018b0b6c-e62e-40b8-988d-944809b07b8a)

Recommended structure:
![Screenshot 2023-07-13 at 2 19 04 PM](https://github.com/splunk/security_content/assets/69353980/2988c599-f704-48d4-9033-e24dd63bdb5a)

### **App Version:**
N/A

**Comment by ljstella** [comment]
Resolved in linked PR
