### ISSUE TITLE
[BUG] `Unusually Long Command Line` Detection has incorrect Risk Message and Threat Object

### ISSUE THREAD

**Issue by ccl0utier** [splunk/security_content#2806]
### Description
The detection `Unusually Long Command Line` [here](https://github.com/splunk/security_content/blob/develop/detections/endpoint/unusually_long_command_line.yml) refers to the `process_name` field using it's CIM datamodel namespace prefix (Processes.process_name) incorrectly.

### **Expected behavior**
Risk Message and Threat Object fixed to use `process_name` correctly.

### **Screenshots**
![image](https://github.com/splunk/security_content/assets/58239192/f423998a-d968-43a1-b369-48df230be033)

![image](https://github.com/splunk/security_content/assets/58239192/9aa8c0c5-e62a-4512-94dc-94952ef43e69)

### **App Version:**
 - ESCU: 4.9.0

**Comment by tccontre** [comment]
thanks for this feedback. this is the fixed for minor bug. 

https://github.com/splunk/security_content/issues/2806
