### ISSUE TITLE
[BUG] Windows Excessive Disabled Services Event uses ComputerName instead of src field (CIM issue)

### ISSUE THREAD

**Issue by iso-rgomez** [splunk/security_content#2825]
### **Describe the bug**
The rule Windows Excessive Disabled Services Event uses ComputerName to store the host affected rather than src (which would be consistent with CIM).  This causes some queries expecting src to be present not to work.

### **Expected behavior**
Execute a rename of the field in the rule so that when it goes to the notable index, views looking for src work correctly.

### **App Version:**
 - ESCU: 4.9.1

**Comment by tccontre** [comment]
thanks for this feedback. I'm on this

**Comment by tccontre** [comment]
apologize for the delay for this issue. the fix will be included in next release.

**Comment by tccontre** [comment]
fix was already in the latest release of ESCU 4.23. thank you again.
