### ISSUE TITLE
[BUG] System Processes Run From Unexpected Locations - missing field for Risk Message

### ISSUE THREAD

**Issue by ccl0utier** [splunk/security_content#2871]
### Description

The rule [System Processes Run From Unexpected Locations](https://github.com/splunk/security_content/blob/develop/detections/endpoint/system_processes_run_from_unexpected_locations.yml) uses the `process_path` field in its Risk Message, but the field is not part of the `tstats` command output fields.

We might want to add it.

### Version

Latest version of ESCU

**Comment by pyth0n1c** [comment]
Thank you @ccl0utier - I have a branch with this change here:
https://github.com/splunk/security_content/pull/2872

**Comment by josehelps** [comment]
I believe this was fixed and shipped thank you again for raising @ccl0utier.
