### ISSUE TITLE
[BUG] - Build Failing Everytime 

### ISSUE THREAD

**Issue by abhinavkakku** [splunk/security_content#2894]
### **Describe the bug**
Trying default Splunk Security COntent to build app, after validation it fails everytime.

### **Expected behavior**
Expecting a app generated that can be imported to SPlunk.

### **Screenshots**
~/de# python contentctl.py -p . build -o build1/escu -pr ESCU

Running Splunk Security Content Control Tool (contentctl)
starting program loaded for TIE Fighter...
      _                                            _
     T T                                          T T
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                   ____                   | |
     | |            ___.r-"`--'"-r.____           | |
     | |.-._,.,---~"_/_/  .----.  \_\_"~---,.,_,-.| |
     | ]|.[_]_ T~T[_.-Y  / \  / \  Y-._]T~T _[_].|| |
    [|-+[  ___]| [__  |-=[--()--]=-|  __] |[___  ]+-|]
     | ]|"[_]  l_j[_"-l  \ /  \ /  !-"_]l_j  [_]~|| |
     | |`-' "~"---.,_\"\  "o--o"  /"/_,.---"~" `-'| |
     | |             ~~"^-.____.-^"~~             | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     l_i                                          l_j -Row

    
Building Splunk App from source ./dist/escu
Copying Splunk App Source to ./dist/escu in preparation for building...done
Validating Splunk App...
/usr/local/lib/node_modules/slim/index.js:25
    const file = _file.endsWith('.graphml') ? _file : `${file}.graphml`;
                                                         ^

ReferenceError: Cannot access 'file' before initialization
    at Command.compileYedFile (/usr/local/lib/node_modules/slim/index.js:25:58)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/slim/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/usr/local/lib/node_modules/slim/node_modules/commander/index.js:914:14)
    at Command.parse (/usr/local/lib/node_modules/slim/node_modules/commander/index.js:717:10)
    at slim (/usr/local/lib/node_modules/slim/index.js:18:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/slim/sli:3:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
error: Command '['slim', 'validate', 'build1/escu/DA-ESS-ContentUpdate']' returned non-zero exit status 1. 
Traceback (most recent call last):
  File "/root/de/bin/contentctl_project/contentctl_core/application/use_cases/build.py", line 60, in validate_splunk_app
    nothing = subprocess.check_output(["slim", "validate", self.output_dir_source])
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['slim', 'validate', 'build1/escu/DA-ESS-ContentUpdate']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/de/contentctl.py", line 461, in <module>
    main(sys.argv[1:])
  File "/root/de/contentctl.py", line 455, in main
    return args.func(args)
  File "/root/de/contentctl.py", line 302, in build
    Build(args)
  File "/root/de/bin/contentctl_project/contentctl_core/application/use_cases/build.py", line 31, in __init__
    self.validate_splunk_app()
  File "/root/de/bin/contentctl_project/contentctl_core/application/use_cases/build.py", line 65, in validate_splunk_app
    raise(Exception(f"Error building Splunk App: {str(e)}"))
Exception: Error building Splunk App: Command '['slim', 'validate', 'build1/escu/DA-ESS-ContentUpdate']' returned non-zero exit status 1.

### **App Version:**
 latest

**Comment by abhinavkakku** [comment]
(de) root@ip-172-31-1-19:~/de# python contentctl.py -p . validate -pr ESCU

Running Splunk Security Content Control Tool (contentctl)
starting program loaded for TIE Fighter...
      _                                            _
     T T                                          T T
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                   ____                   | |
     | |            ___.r-"`--'"-r.____           | |
     | |.-._,.,---~"_/_/  .----.  \_\_"~---,.,_,-.| |
     | ]|.[_]_ T~T[_.-Y  / \  / \  Y-._]T~T _[_].|| |
    [|-+[  ___]| [__  |-=[--()--]=-|  __] |[___  ]+-|]
     | ]|"[_]  l_j[_"-l  \ /  \ /  !-"_]l_j  [_]~|| |
     | |`-' "~"---.,_\"\  "o--o"  /"/_,.---"~" `-'| |
     | |             ~~"^-.____.-^"~~             | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     l_i                                          l_j -Row

    
Getting MITRE Attack Enrichment Data. This may take some time...
                 Client: [100%]...Done!
             Enterprise: [100%]...Done!
          Relationships: [100%]...Done!
                 Groups: [100%]...Done!
	MITRE Technique Progress: [100%]...Done!
Creating Security Content - ESCU. This may take some time...
       Lookups Progress: [100%]...Done!
        Macros Progress: [100%]...Done!
   Deployments Progress: [100%]...Done!
     Baselines Progress: [100%]...Done!
Investigations Progress: [100%]...Done!
     Playbooks Progress: [100%]...Done!
    Detections Progress: [100%]...Done!
       Stories Progress: [100%]...Done!
Validation of security content successful.
(de) root@ip-172-31-1-19:~/de# python contentctl.py -p . generate -o dist/escu -pr ESCU

Running Splunk Security Content Control Tool (contentctl)
starting program loaded for TIE Fighter...
      _                                            _
     T T                                          T T
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                   ____                   | |
     | |            ___.r-"`--'"-r.____           | |
     | |.-._,.,---~"_/_/  .----.  \_\_"~---,.,_,-.| |
     | ]|.[_]_ T~T[_.-Y  / \  / \  Y-._]T~T _[_].|| |
    [|-+[  ___]| [__  |-=[--()--]=-|  __] |[___  ]+-|]
     | ]|"[_]  l_j[_"-l  \ /  \ /  !-"_]l_j  [_]~|| |
     | |`-' "~"---.,_\"\  "o--o"  /"/_,.---"~" `-'| |
     | |             ~~"^-.____.-^"~~             | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     l_i                                          l_j -Row

    
Getting MITRE Attack Enrichment Data. This may take some time...
                 Client: [100%]...Done!
             Enterprise: [100%]...Done!
          Relationships: [100%]...Done!
                 Groups: [100%]...Done!
	MITRE Technique Progress: [100%]...Done!
Creating Security Content - ESCU. This may take some time...
       Lookups Progress: [100%]...Done!
        Macros Progress: [100%]...Done!
   Deployments Progress: [100%]...Done!
     Baselines Progress: [100%]...Done!
Investigations Progress: [100%]...Done!
     Playbooks Progress: [100%]...Done!
    Detections Progress: [100%]...Done!
       Stories Progress: [100%]...Done!
Generate of security content successful.
(de) root@ip-172-31-1-19:~/de# python contentctl.py -p . build -o build1/escu -pr ESCU

Running Splunk Security Content Control Tool (contentctl)
starting program loaded for TIE Fighter...
      _                                            _
     T T                                          T T
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                   ____                   | |
     | |            ___.r-"`--'"-r.____           | |
     | |.-._,.,---~"_/_/  .----.  \_\_"~---,.,_,-.| |
     | ]|.[_]_ T~T[_.-Y  / \  / \  Y-._]T~T _[_].|| |
    [|-+[  ___]| [__  |-=[--()--]=-|  __] |[___  ]+-|]
     | ]|"[_]  l_j[_"-l  \ /  \ /  !-"_]l_j  [_]~|| |
     | |`-' "~"---.,_\"\  "o--o"  /"/_,.---"~" `-'| |
     | |             ~~"^-.____.-^"~~             | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     | |                                          | |
     l_i                                          l_j -Row

    
Building Splunk App from source ./dist/escu
Copying Splunk App Source to ./dist/escu in preparation for building...done
Validating Splunk App...
/usr/local/lib/node_modules/slim/index.js:25
    const file = _file.endsWith('.graphml') ? _file : `${file}.graphml`;
                                                         ^

ReferenceError: Cannot access 'file' before initialization
    at Command.compileYedFile (/usr/local/lib/node_modules/slim/index.js:25:58)
    at Command.listener [as _actionHandler] (/usr/local/lib/node_modules/slim/node_modules/commander/index.js:413:31)
    at Command._parseCommand (/usr/local/lib/node_modules/slim/node_modules/commander/index.js:914:14)
    at Command.parse (/usr/local/lib/node_modules/slim/node_modules/commander/index.js:717:10)
    at slim (/usr/local/lib/node_modules/slim/index.js:18:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/slim/sli:3:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
error: Command '['slim', 'validate', 'build1/escu/DA-ESS-ContentUpdate']' returned non-zero exit status 1. 
Traceback (most recent call last):
  File "/root/de/bin/contentctl_project/contentctl_core/application/use_cases/build.py", line 60, in validate_splunk_app
    nothing = subprocess.check_output(["slim", "validate", self.output_dir_source])
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['slim', 'validate', 'build1/escu/DA-ESS-ContentUpdate']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/de/contentctl.py", line 461, in <module>
    main(sys.argv[1:])
  File "/root/de/contentctl.py", line 455, in main
    return args.func(args)
  File "/root/de/contentctl.py", line 302, in build
    Build(args)
  File "/root/de/bin/contentctl_project/contentctl_core/application/use_cases/build.py", line 31, in __init__
    self.validate_splunk_app()
  File "/root/de/bin/contentctl_project/contentctl_core/application/use_cases/build.py", line 65, in validate_splunk_app
    raise(Exception(f"Error building Splunk App: {str(e)}"))
Exception: Error building Splunk App: Command '['slim', 'validate', 'build1/escu/DA-ESS-ContentUpdate']' returned non-zero exit status 1.

**Comment by ljstella** [comment]
Hey @abhinavkakku, what is it that you're trying to accomplish? If you take a look at the CI pipeline used for building ESCU (`.github/workflows/build-and-validate.yml`), the build command isn't used. I don't believe it was finished in this version of contentctl. 

Depending on what you're trying to do, you may want to look into using the new dedicated [contentctl codebase](https://github.com/splunk/contentctl)

**Comment by abhinavkakku** [comment]
@ljstella  sure I will try that new contentctl codebase.

I am only trying to use this Security Content as documented, and failing to build app that can be deployed to Splunk.

Possibly I need to understand more about this whole thing.

**Comment by ljstella** [comment]
If you're just looking for the app itself, its available on [Splunkbase](https://splunkbase.splunk.com/app/3449) as well as the DA-ESS-ContentUpdate-<version>.tar.gz tarball on each of the [releases.](https://github.com/splunk/security_content/releases)
