### ISSUE TITLE
Include `tags.atomic_guid` and `tags.required_fields` into ESCU

### ISSUE THREAD

**Issue by ccl0utier** [splunk/security_content#2904]
**Is your feature request related to a problem? Please describe.**
Could the team expose `tags.atomic_guid` and `tags.required_fields` in ESCU please?  That would help a lot track this important information into other apps that "augment" ES or directly via REST.

**Describe the solution you'd like**
For those fields to be included in the `savedsearches.conf` information in ESCU.

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="788" alt="image" src="https://github.com/splunk/security_content/assets/58239192/9c78ead4-8d42-4f1f-843b-f5f2d7409571">

**Comment by patel-bhavin** [comment]
We no longer maintain required fields, please refer to the data_source yaml file to find more information about the event!

atomic guid is now shipped in ss.conf : Example:

```action.escu.atomic_red_team_guids = ["7e47ee60-9dd1-4269-9c4f-97953b183268"]```
