### ISSUE TITLE
[BUG] "Kerberos TGT Request Using RC4 Encryption" using non-CIM field "Account_Name"

### ISSUE THREAD

**Issue by iso-rgomez** [splunk/security_content#2920]
### **Describe the bug**
The rule "Kerberos TGT Request Using RC4 Encryption" in 4.16.0 uses the non-CIM field "Account_Name" rather than the standard field "user".  This doesn't appear to have been the case as recently as 4.14.0; our allowlisting in the macro `kerberos_tgt_request_using_rc4_encryption_filter` used the field "user" and operated as expected, breaking only during an upgrade performed today.

### **Expected behavior**
The field "user" should be utilized in order to ensure queries looking for that CIM field in the notable index find Notables related to this rule.

### **App Version:**
 - ESCU: 4.16.0

**Comment by josehelps** [comment]
This detection does not operate against a datamodel but instead against the raw Windows event logs hence, it is not using a CIM field. Can you give me an example of what you believe the "fixed" query should look like?

**Comment by patel-bhavin** [comment]
@iso-rgomez : thank you for raising the issue! this search has been updated to use the xml format logs since the issue was created! Closing this issue as it is old now! Please feel free to open a new issue if the updated query has issues!
