### ISSUE TITLE
[BUG] O365 Mailbox Inbox Folder Shared with All Users. Field "object" doesn't exist. 

### ISSUE THREAD

**Issue by atgithub11** [splunk/security_content#2937]
Correlation search, **O365 Mailbox Inbox Folder Shared with All Users**, is currently using a field called "object", as object=Inbox. But I do not see this field being sent as part of O365 exchange data. Instead, I see a field called Item.ParentFolder.Name with values such as Inbox, Calender, Contacts etc. 

Should "object=Inbox" be replaced with "Item.ParentFolder.Name=Inbox" for this correlation search? 

### **App Version:**
 - ESCU: 4.18.0

**Comment by josehelps** [comment]
@atgithub11 this might be due to how the data for o365 is being collected in your environment. I believe for this detection we expect the user to be leveraging https://splunkbase.splunk.com/app/4055 let me know if this is the case?

**Comment by nasbench** [comment]
Hey @atgithub11 thanks for opening this issue. Here is some clarification that might help you understand this.

You can see in the [detection](https://github.com/splunk/security_content/blob/develop/detections/cloud/o365_mailbox_inbox_folder_shared_with_all_users.yml), the raw log does contain the field "Item.ParentFolder.Name"

![image](https://github.com/user-attachments/assets/1df8ce81-dd15-43f3-a0c2-f1bb536aa298)

And this is what you are probably ingesting.

But as @josehelps said, the analytics expects ingestion of O365 via the splunk app https://splunkbase.splunk.com/app/4055 as it is stated by the how to implement section

```yml
how_to_implement: You must install the Splunk Microsoft Office 365 Add-on and ingest Office 365 management activity events.
```

Behind the scene, this app is creating the field object and assigning its value based on some condition:

![image](https://github.com/user-attachments/assets/3aab3fb1-47d8-4ba3-8592-93101c884329)

In this case if the Operation field is "ModifyFolderPermissions" or "AddFolderPermissions", the value of the Object field will be set to `Item.ParentFolder.Name`.

Hence the detection should be correct, and this is just an issue of ingestion.

Hope this helps.

I'll be closing this as complete, feel free to re-open the issue in case you have further questions
