### ISSUE TITLE
[BUG] - Unknown Process Using The Kerberos Protocol is too noisy

### ISSUE THREAD

**Issue by wkleinhenz** [splunk/security_content#2943]
### **Describe the bug**
The way that this detection attempts to join solely on the process_id leads to a large number of false positives due to how windows reuses process_ids , this issue was originally referenced back in  #2565 but that issue was closed without changing the referenced search either in terms of removing the use of join or fixing the joining issue.

### **Expected behavior**
At least the search should be able to correctly merge processes using both the id and dest host

I believe this could be done simply by joining on both dest and process_id however i have not tested this significantly

### **App Version:**
 - ESCU: 4.18.0

**Comment by patel-bhavin** [comment]
Hello @wkleinhenz Thanks for re-raising the issue. We may have missed updating this detection correctly in the past!
We updated this search to join on both dest and process_id. Will ship this updated detections in the next release!

Please feel free to create issues for things like this and we really appreciate you!!]! 

Note: We couldnt use the process_guid field which would have been more accurate but the network traffic datamodel doesnt have that field.

**Comment by patel-bhavin** [comment]
Here's how to the new search looks like : 
```
| tstats `security_content_summariesonly` count FROM datamodel=Endpoint.Processes where Processes.process_name!=lsass.exe by _time Processes.process_id Processes.process_name Processes.dest Processes.process_path Processes.process Processes.parent_process_name 
| `drop_dm_object_name(Processes)` 
| `security_content_ctime(firstTime)` 
| `security_content_ctime(lastTime)` 
| join process_id dest 
    [| tstats `security_content_summariesonly` count FROM datamodel=Network_Traffic.All_Traffic where All_Traffic.dest_port = 88 by All_Traffic.src All_Traffic.process_id All_Traffic.dest_port 
    | `drop_dm_object_name(All_Traffic)` 
    | rename src as dest ] 
| table _time dest parent_process_name process_name process_path process process_id dest_port 
| `unknown_process_using_the_kerberos_protocol_filter````


Note: to better avoid collisions, process_guid field is better however the Network DM currently has limitation from using that.

**Comment by patel-bhavin** [comment]
Please feel free to reopen this issue if it persists! Thank you
