### ISSUE TITLE
[BUG] Linux Service Started Or Enabled triggering on Windows events

### ISSUE THREAD

**Issue by 0xC0FFEEEE** [splunk/security_content#2944]
### **Describe the bug**
The Linux Service Started Or Enabled rule can trigger on Windows events.

### **Expected behavior**
Rule does not trigger on events from Windows Sysmon

### **Screenshots**
![image](https://github.com/splunk/security_content/assets/119874251/be2df22b-adbc-46ec-a10c-218f64f5d57e)

### **App Version:**
 - ESCU: 4.18.0

### **Additional context**
I got a good laugh out of this.

Appending `NOT Processes.os="Microsoft Windows"` to the end of the `where` clause seems sufficient for resolving this issue.

**Comment by josehelps** [comment]
oh man, that is 1 for the data models and 0 for the detections, thank you for raising this! Will make sure its patched on our next release.

**Comment by 0xC0FFEEEE** [comment]
Thanke @josehelps 

I think the score is even. I've had to further update the filter with the following as the CIM datamodel is inconsistent between Sysmon and the Security Channel:

```
NOT (Processes.os="Microsoft Windows" OR Processes.vendor_product="Microsoft Windows")
```

**Comment by nasbench** [comment]
This was resolved in https://github.com/splunk/security_content/commit/0078f83d9532605bbdc43e6e7640b0fd487b805a

![image](https://github.com/user-attachments/assets/7cb79342-9cb3-43da-8bcb-862c013e2e6a)

Closing this as completed.
