### ISSUE TITLE
Consider adding Scope for search Azure AD Tenant Wide Admin Consent Granted

### ISSUE THREAD

**Issue by atgithub11** [splunk/security_content#2950]
https://research.splunk.com/cloud/dc02c0ee-6ac0-4c7f-87ba-8ce43a4e4418/

Search is currently extracting ConsentType. Please also consider extracting Scope as that would provide useful context around this detection. These are the permissions granted. 

| rex field=new_field "ConsentType: (?<ConsentType>[^\,]+).***Scope: (?<Scope>[^\,]+)**"

**Comment by mvelazc0** [comment]
thats a good idea. The detection will be updated on the next release.

Thanks!
