### ISSUE TITLE
[BUG] Datasource is set incorrectly on this detection

### ISSUE THREAD

**Issue by josehelps** [splunk/security_content#2962]
Today linux detections point to Sysmon Event Code 1 data source that has no Linux TA pointer, we may need a Linux data source. 

https://github.com/splunk/security_content/blob/develop/detections/endpoint/linux_clipboard_data_copy.yml

points to: https://github.com/splunk/security_content/blob/develop/data_sources/endpoint/Sysmon_Event_ID_1.yml 

We should somehow add validation to this.

**Comment by patel-bhavin** [comment]
This has been fixedwith Patrick's updates
