### ISSUE TITLE
[BUG] ESCU - Get ADUser with PowerShell - Rule has no Adaptive Reponse Actions

### ISSUE THREAD

**Issue by albertenc13** [splunk/security_content#2965]
Is it normal that the ESCU - Get ADUser with PowerShell - Rule has no Adaptive Reponse Actions (DA-ESS-ContentUpdate 4.24.0)?

![image](https://github.com/splunk/security_content/assets/149427123/10da7a2c-07bb-4e7e-a504-adadb1b818da)

**Comment by ljstella** [comment]
Hi @albertenc13 

Thanks for reaching out. The [Get ADUser with Powershell](https://research.splunk.com/endpoint/0b6ee3f4-04e3-11ec-a87d-acde48001122/) rule is configured as designed. 

There are several analytics that ship within ESCU that do not have an Adaptive Response Action. These are all "Hunting" type analytics, which means they're written with the intent to be used to help with Threat Hunting, run interactively by an analyst familiar enough with the environment to recognize what activity returned by it is "normal" or "not normal" for them. Alternatively, users can build a dashboard around the analytic that can have additional searches to provide more context or to provide instructions to the analyst interpreting the results.

You can read more about the different types of analytics within ESCU, and how that type influences the adaptive response actions that are preconfigured [here.](https://github.com/splunk/security_content/wiki/Detection-Analytic-Types)

**Comment by josehelps** [comment]
@albertenc13 hope this helps, would love to hear any feedback you have but otherwise for now I will close this issue.

**Comment by albertenc13** [comment]
Hi @josehelps  and @ljstella this is actually very useful and informative! thank you so mcuh for all of the hardwork you guys put into creating these detections specially for small teams like mine where we do not have a detection engeerning team!!
