### ISSUE TITLE
Scheduled Task Initiation on Remote Endpoint - Update Analytics

### ISSUE THREAD

**Issue by Badoodish** [splunk/security_content#2977]
One of the current filters: `Processes.process=*/s*` creates false positives because it matches on the `/sc` switch/argument for the schtasks.exe binary.
Recommend adding a space character like so: `Processes.process=*/s *`

**Comment by patel-bhavin** [comment]
Thank you @Badoodish : We have fixed this SPL and will ship an updated version shortly! appreciate the details in here.

**Comment by patel-bhavin** [comment]
shipped in 4.37.0! Thank you!
