### ISSUE TITLE
[BUG] please, fix links in wiki: https://github.com/splunk/security_content/wiki/Detection-Analytic-Types

### ISSUE THREAD

**Issue by yaroslav-nakonechnikov** [splunk/security_content#3011]
It is not possible to talk with SOC analysts, when links in wiki are broken

https://github.com/splunk/security_content/wiki/Detection-Analytic-Types

just check "[Baseline Of Cloud Infrastructure API Calls Per User](https://github.com/splunk/security_content/blob/develop/baselines/baseline_of_api_calls_per_user_arn.ymlhttps://github.com/splunk/security_content/blob/develop/detections/cloud/baseline_of_cloud_infrastructure_api_calls_per_user.yml)" for example

**Comment by ljstella** [comment]
Thanks, we've fixed that link.
