### ISSUE TITLE
[BUG] browser_app_list lookup doesn't exist in indexers, causing query to fail in "Windows Credential Access From Browser Password Store"

### ISSUE THREAD

**Issue by iso-rgomez** [splunk/security_content#3014]
### **Describe the bug**
When ESCU is loaded onto a Splunk ES system that relies on non-ES Splunk indexers, the query refers to a table that does not exist on the indexer, causing the query to fail.

### **Expected behavior**
The query runs without errors on the Splunk ES search head, without relying on the indexers to have the lookup table as well. This can be fixed by changing the "lookup browser_app_list" command to "lookup local=true browser_app_list".

### **Screenshots**
![lookup_table_fail](https://github.com/splunk/security_content/assets/96446231/c81505c3-e349-4774-967b-93212f2e7076)

### **App Version:**
 - ESCU: 4.31.1

**Comment by ljstella** [comment]
Hey @iso-rgomez 

This should be fixed now, v4.33 had several searches rewritten to avoid this issue in distributed search environments.
