### ISSUE TITLE
[BUG] - Windows AD Domain Replication ACL Addition has unnecessary escape chars in SPL causing errors

### ISSUE THREAD

**Issue by livehybrid** [splunk/security_content#3039]
## **If you have a Splunk Support contract, creating a support case for your issue may result in faster resolution.**
Raised ([3531433])

### **Describe the bug**
The current SPL for `ESCU - Windows AD Domain Replication ACL Addition - Rule` is:
```
`wineventlog_security`  | rex field=AttributeValue max_match=10000 \"OA;;CR;89e95b76-444d-4c62-991a-0facbeda640c;;(?P<DSRGetChangesFiltered_user_sid>S-1-[0-59]-\d{2}-\d{8,10}-\d{8,10}-\d{8,10}-[1-9]\d{3})\)\"| table _time dest src_user DSRGetChanges_user_sid DSRGetChangesAll_user_sid DSRGetChangesFiltered_user_sid| mvexpand DSRGetChanges_user_sid| eval minDCSyncPermissions=if(DSRGetChanges_user_sid=DSRGetChangesAll_user_sid,\"true\",\"false\"), fullSet=if(DSRGetChanges_user_sid=DSRGetChangesAll_user_sid AND DSRGetChanges_user_sid=DSRGetChangesFiltered_user_sid,\"true\",\"false\")| where minDCSyncPermissions=\"true\" | lookup identity_lookup_expanded  objectSid as DSRGetChanges_user_sid OUTPUT sAMAccountName as user | rename DSRGetChanges_user_sid as userSid | stats min(_time) as _time values(user) as user by dest src_user userSid minDCSyncPermissions fullSet| `windows_ad_domain_replication_acl_addition_filter`
```
However this contains escaped quotes which should not be escaped in the rex and eval commands. This is returning an error "**Unknown search command '0'.**"

### **Expected behavior**
The search should parse and be executable without errors.

### **Screenshots**
<img width="1572" alt="image" src="https://github.com/user-attachments/assets/3c93b183-c78b-4733-872a-e9b7b05a7bca">

### **App Version:**
 - ESCU: 4.36.0

**Comment by patel-bhavin** [comment]
@livehybrid : Thank you for fixing this search and offering a PR. We will have this released in ESCU 4.37.0!
