### ISSUE TITLE
[BUG] Azure MFA failure detections logic flaw

### ISSUE THREAD

**Issue by 0xC0FFEEEE** [splunk/security_content#3134]
There are a number of Azure MFA failure based detections utilizing `properties.status.errorCode=500121` as a means of detecting one or more MFA auth failures. There's nothing wrong with this in of itself, however upon noticing a greater number of notables than anticipated with these detections enabled and performing some testing and research I have found the following from [here](https://learn.microsoft.com/en-us/entra/identity/monitoring-health/concept-sign-in-log-activity-details):

> Multifactor authentication: When a user signs in with MFA, several separate MFA events are actually taking place. For example, if a user enters the wrong validation code or doesn't respond in time, more MFA events are sent to reflect the latest status of the sign-in attempt. These sign-in events appear as one line item in the Microsoft Entra sign-in logs. **That same sign-in event in Azure Monitor, however, appears as multiple line items. These events all have the same correlationId.**

Note the last sentence.

Testing confirms that failed MFA does indeed result in more than one event for a single ocurrence of MFA auth. In addition to the above statement, it turns out that the `correlationId` can span multiple MFA auth attempts, however the `originalRequestId` field is unique for each attempt.

As an example of what this should look like, using `Azure AD Authentication Failed During MFA Challenge` as a basis for an updated search:

```
`azure_monitor_aad` category=SignInLogs properties.status.errorCode=500121 
| rename properties.* as * 
| stats count, min(_time) as firstTime, max(_time) as lastTime, values(user) as user, values(src_ip) as src_ip, values(mfaDetail.authMethod) as mfa_method, values(status.additionalDetails) as status.additionalDetails, values(reason) as reason, values(appDisplayName) as appDisplayName, values(user_agent) as user_agent by correlationId, originalRequestId
| `security_content_ctime(firstTime)` 
| `security_content_ctime(lastTime)` 
| `security_content_ctime(times)` 
| `azure_ad_authentication_failed_during_mfa_challenge_filter`
```

`correlationId` can be thought of as the login session, and `originalRequestId` the MFA attempt. `count` is effectively useless above, but is left in to hightlight the fact that multiple events are produced for each failed attempt.

It's also worth noting that there is inconsistent data returned by Azure AD. Multiple MFA failures .e.g. `MFA denied; user declined the authentication` can yield inconsistent/missing values in `status.additionalDetails` between attempts, and either the objectid or actual username (or both!) for the user field.

### **App Version:**
 - ESCU: 4.40.0

**Comment by patel-bhavin** [comment]
That's a great suggestion @0xC0FFEEEE! Do you mind creating a PR with these fixes and I can help you get started with it Also, please add your name to the author section. I think it would be a great contribution!

**Comment by 0xC0FFEEEE** [comment]
Will do @patel-bhavin 👍🏼 

Need to do a little more investigation in to this before I raise a PR.

Contrary to Microsofts documentation, on occasion an `originalRequestId` can consist of multiple MFA attempts under as yet undetermined circumstances, which results in a failed MFA message alongside a successful message in the `status.additionalDetails` field as grouped in my suggestion above (I suspect it relates to desktop app auth attempts such as MS Teams, but not yet proven).

It turns out that Microsoft also produces a single summary event some time (~5mins) after an attempt which contains the full history of the auth attempt. This appears to be the single event that can be found in the audit logs in the Azure portal. I need to test an alternative approach using something to the effect of the following to try and replicate what can be observed in the portal.

```
`azure_monitor_aad` category=SignInLogs properties.status.errorCode=500121 
| rename properties.* as * 
| dedup correlationId, originalRequestId
```To do - mvexpand the relevant nested array containing the authentication summary```
```
