### ISSUE TITLE
[BUG] research.splunk.com not showing datasources correctly when looking at a specific detection

### ISSUE THREAD

**Issue by isakhansson** [splunk/security_content#3195]
### **Describe the bug**
When looking through https://research.splunk.com/detections/ there are detection rules with multiple data sources. If you open up a specific detection rule it seems to only show the first data source in the list of data sources. For example on the detection rule Windows AdFind Exe we see the following data sources from the /detections/ website:
CrowdStrike ProcessRollup2, Windows icon Sysmon EventID 1, Windows icon Windows Event Log Security 4688

But if we open up Windows AdFind Exe specifically https://research.splunk.com/endpoint/bd3b0187-189b-46c0-be45-f52da2bae67f/ it only lists CrowdStrike ProcessRollup2 as a data source.

This seems to be the case with other detection rules as well.

### **Expected behavior**
All data sources should be shown when looking at a specific detection rule.

### **Screenshots**
![detections](https://github.com/user-attachments/assets/24ee2aec-ecfe-4f3a-a46c-1fe05151bcf4)
![specific_detection](https://github.com/user-attachments/assets/0991d874-c06c-4191-9973-994bb50e2b40)

### **App Version:**
 - Firefox 131.0.3
 - Edge Version 130.0.2849.56

**Comment by ljstella** [comment]
Thanks for the report- we've been tracking this for a bit and are almost ready to ship a fix. We'll circle back and close this once it ships.

**Comment by ljstella** [comment]
These are now fixed.
