### ISSUE TITLE
We should have 1 data set per test files

### ISSUE THREAD

**Issue by josehelps** [splunk/security_content#818]
https://github.com/splunk/security-content/blob/fc62a736fa257f97a3fa2075572777ae9d5a0e23/tests/T1003_001.yml#L21-L29

It is a bit confusing since it is not clear which test file matches what detection given

**Comment by P4T12ICK** [comment]
In this case it was not needed but there will be cases in which a detection needs logs from different sources, e.g. a powershell event and a sysmon event.

**Comment by P4T12ICK** [comment]
that's why it's an array of in attack_data

**Comment by josehelps** [comment]
makes sense closing, thank you for the explanation, closing!
