### ISSUE TITLE
 ESCU - AWS Cloud Provisioning From Previously Unseen City - Rule - "[subsearch]: The lookup table 'previously_seen_provisioning_activity_src.csv' requires a .csv or KV store lookup definition."

### ISSUE THREAD

**Issue by kkolli4** [splunk/security_content#828]

**Comment by kkolli4** [comment]
![Uploading Screen Shot 2020-10-23 at 4.44.47 PM.png…]()

**Comment by patel-bhavin** [comment]
@kkolli4 :Hey Durga, `ESCU - AWS Cloud Provisioning From Previously Unseen City - Rule` - this particular search name is not in the list of Beta searches listed here: https://docs.google.com/spreadsheets/d/1K8xMy3jX_PeF__QU-0sP-r7n2HwMMUQpnYfvHF_rEi4/edit#gid=1166574115

I think you want to look for and test  `ESCU - Cloud Provisioning From Previously Unseen City - Rule` .

Note: the updated search name for Mustang does not have `AWS` in the search title

**Comment by patel-bhavin** [comment]
also, Thank you @kkolli4 for pointing out naming inconsistency: I have updated the sheet with correct titles

**Comment by patel-bhavin** [comment]
The previous search `AWS Cloud Provisioning From Previously Unseen City` still shows an error but we intend to deprecate it since customers should use the latest Change Datamodel(yet to be released)
