### ISSUE TITLE
Analytic Story Dashboard not showing the story details

### ISSUE THREAD

**Issue by dbuchberger** [splunk/security_content#902]
The Analytic Story Page seems to be broken or at least missing the Panel that should display the details of the chosen Analytic Story from the dropdown.

**Comment by jzsplunk** [comment]
@dbuchberger are all analytics_storys broken for you or just a particular one do happen to have a screenshot? Or information on what branch you are testing on?  I just tested locally on the latest develop bits and have not run into an issue on my local splunk test instance.

**Comment by dbuchberger** [comment]
@jzsplunk thanks for the fast response. So I first tried with the 3.0.8 version out of github, did all the needed steps (verification, build, etc until the finished spl file) uploaded the spl and the Analytic story is completely empty (as seen in the attached screenshot). Then I thought maybe I did something wrong and fetched the 3.0.8 version out of the splunk app store and had the same issue. Maybe I am completely missing something or doing something wrong?[
![security_content_issue_3_0_8](https://user-images.githubusercontent.com/74184118/98643811-d477fb00-232f-11eb-945a-895c77c239ca.PNG)
](url)

**Comment by dbuchberger** [comment]
btw it doesnt matter what analytic story I choose in the drop down nothing is happening.
EDIT: now I also tested with the new 3.0.9 version but still no details are shown - am I missing something completely?

**Comment by patel-bhavin** [comment]
@dbuchberger : It could be a browser problem with the javascript file, have you tried using any other browser?

**Comment by dbuchberger** [comment]
@patel-bhavin I tried edge, chrome and firefox - but I have the same issue with every single browser

**Comment by patel-bhavin** [comment]
yeah, this is strange. Did you try clearing the cache files?! We havent been able to replicate this issue on our end. 

Can you please send us (research@splunk.com) a [HAR export](https://help.o2.verizonmedia.com/hc/en-us/articles/360000074523-How-to-Save-a-HAR-File-Log-in-Google-Chrome) from developer tools with a screen shot, that might help us debug. 

Happy to jump on a zoom call as well

**Comment by dbuchberger** [comment]
so emptying the cache didnt help with my package (forked and build the spl - then uploaded the file) but I wanted to give it a try and removed the app completely, got the 3.0.8 version out of the app store and cleared the cache - now the site is shown correctly and its working - thanks

**Comment by patel-bhavin** [comment]
awesome! thanks for the update
