### ISSUE TITLE
ESCU - Previously Seen Cloud Instance Modifications By User - Update - Error in 'outputlookup' command: The lookup table 'previously_seen_cloud_instance_modificationss_by_user' is invalid.

### ISSUE THREAD

**Issue by sgopalakrishnan5** [splunk/security_content#927]
ESCU version - https://repo.splunk.com/artifactory/webapp/#/artifacts/browse/tree/General/Solutions/DA/da-ess-contentupdate/builds/escu_mustang/bugfix/0.0.5/DA-ESS-ContentUpdate-3.0.9.tar.gz

Looks like a typo in outputlookup previously_seen_cloud_instance_modificationss_by_user which must be outputlookup previously_seen_cloud_instance_modifications_by_user

The current spl errors out - Error in 'outputlookup' command: The lookup table 'previously_seen_cloud_instance_modificationss_by_user' is invalid.

![Screen Shot 2020-11-13 at 3 22 26 PM](https://user-images.githubusercontent.com/71671922/99130172-74e64d80-25c4-11eb-91b8-e090c4ac9df3.png)

**Comment by patel-bhavin** [comment]
Thanks for filing this: currently tracking this fix in this branch: `mustang_beta_drop3`
