### ISSUE TITLE
ESCU - Cloud Instance Modified By Previously Unseen User - Rule - Error in 'SearchParser': Mismatched ']'.

### ISSUE THREAD

**Issue by sgopalakrishnan5** [splunk/security_content#932]
ESCU version - https://repo.splunk.com/artifactory/webapp/#/artifacts/browse/tree/General/Solutions/DA/da-ess-contentupdate/builds/escu_mustang/bugfix/0.0.5/DA-ESS-ContentUpdate-3.0.9.tar.gz

Search has mismatched ] which needs to be removed.
Error in 'SearchParser': Mismatched ']'.

![Screen Shot 2020-11-16 at 4 25 37 PM](https://user-images.githubusercontent.com/71671922/99324122-6f893d00-2828-11eb-877f-b149e4c6ed50.png)

**Comment by patel-bhavin** [comment]
This search didn't get updated since it wasn't scoped for Beta 2. Updated the search logic and also generated test dataset for testing. Thank you for filing this issue
