### ISSUE TITLE
ER - Support custom alert actions

### ISSUE THREAD

**Issue by inspired** [splunk/security_content#939]
As a user I would like to be able to define my detections with custom alert actions besides "notable", "risk" and "email". An example of a custom alert action would be "sendtophantom"

We should support the alert actions listed above or allow custom built-in alert actions (not on our pre-defined list), as well as additional params necessary for i.e. integration with ticketing systems or similar.

Whether this should be done using tags, on a deployment or detection level is something I'll leave up to you.

Discussed with @P4T12ICK

**Comment by phplucas** [comment]
@inspired @P4T12ICK no updates here?

**Comment by inspired** [comment]
As a side note **sendtophantom** may not be the best example because the Notable Event ID has not yet been generated (it gets generated by the Notable Alert Action). In this case a scheduled search on BACKTICKSnotableBACKTICKS is probably the way to go

**Comment by nbheu1** [comment]
It would be great to be able to have ES adapative responses to use as own objects to attach to detection rules and/or analytical stories. Detection's need also to support throttle period, so SOC analyst can adjust the alert mechanisms.

**Comment by P4T12ICK** [comment]
Sorry for my ate reply. We should work on supporting some more alert actions. I will have a look into ES adaptive responses. Adding Throttling should be an easy fix.
