### ISSUE TITLE
The Risk object field for this search - "ESCU - Cloud Instance Modified By Previously Unseen User - Rule" should be set to user instead of src_user. 

### ISSUE THREAD

**Issue by sgopalakrishnan5** [splunk/security_content#941]
The Risk object field for this search - "ESCU - Cloud Instance Modified By Previously Unseen User - Rule" should be set to user instead of src_user. Risk events don't get written into index="risk" otherwise.

Version: https://repo.splunk.com/artifactory/webapp/#/artifacts/browse/tree/General/Solutions/DA/da-ess-contentupdate/builds/escu_mustang/bugfix/0.0.6/DA-ESS-ContentUpdate-3.9.0.tar.gz

**Comment by patel-bhavin** [comment]
fixed and uploaded to a new link : https://repo.splunk.com/artifactory/webapp/#/artifacts/browse/tree/General/Solutions/DA/da-ess-contentupdate/builds/escu_mustang/bugfix/0.0.7/DA-ESS-ContentUpdate-3.9.0.tar.gz
