### ISSUE TITLE
"ESCU - Add Prohibited Processes to Enterprise Security" - Wrong field used for lookup

### ISSUE THREAD

**Issue by my2ndhead** [splunk/security_content#950]
The search updates the existing process table `interesting_processes_lookup` from ES with data from ESCU's `prohibitedProcesses_lookup`.

The `interesting_processes_lookup` lookup table contains a column `app` which is used as an input-field within the `get_interesting_processes` macro as follows:

`lookup interesting_processes_lookup app as process,dest OUTPUTNEW is_required,is_prohibited.is_secure,note`

According to CIM the process contains the full command string of the spawned process.

Either the macro should be changed to use `process_name` as the input field, or the `interesting_processes_lookup` respectively the `prohibitedProcesses_lookup` should contain full command strings.

**Comment by P4T12ICK** [comment]
Thank you for your great feedback. We are currently in the process of retesting all our detections.

**Comment by josehelps** [comment]
@my2ndhead had a challenge finding the detection you are referencing, mind including a link in here. We do have a `prohibited_processes` under `/lookups`. We did deprecated https://github.com/splunk/security-content/blob/develop/detections/deprecated/prohibited_software_on_endpoint.yml but is fairly different than what you are describing above.

**Comment by my2ndhead** [comment]
@d1vious Looks like the search was deprecated: [https://github.com/splunk/security-content/blob/develop/baselines/deprecated/add_prohibited_processes_to_enterprise_security.yml](url)

Closing this issue.
