### ISSUE TITLE
"Endpoint - Anomalous New Services -Rule" fires for service="unknown"

### ISSUE THREAD

**Issue by my2ndhead** [splunk/security_content#963]
The "Endpoint - Anomalous New Services -Rule" should filter out services that are "unknown". 

There are many Windows EventIDs which are tagged with `service` and `report` in the endpoint data model without having a value for "service" They will end up being set to service="unknown".

Looking at the EventIDs (over 60 at my customer!). There's no easy way to do a service mapping. Maybe it's better to exclude events with service="unknown" from alerting for the moment.

**Comment by patel-bhavin** [comment]
@my2ndhead : This.  search is from SA-EndpointProtection (Enterprise Security ships it) and not from ESCU. Probably creating a SOLNESS ticket is more relevant here
